### ISSUE TITLE
T5 Update indicators according to structure of final dataset

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#105]
Dear @maurolepore , 

this task is still blocked but I already wanted to document it for next week's sprint. Once we have the output from the matching process from Mirja and Bob, we probably need to update some of the indicators according to the new data. 

[Link to respective overview ticket](https://github.com/2DegreesInvesting/tiltData/issues/242).

**Comment by maurolepore** [comment]
Updates:

* Mirja shared the data [here](https://2investinginitiative.slack.com/archives/C02NDH6SD3P/p1681225266208129)
* Tilman shared an overview of our data pipeline [here](https://2investinginitiative.slack.com/archives/C050VAQACC9/p1681399559047799)

**Comment by maurolepore** [comment]
This is obsolete
