### ISSUE TITLE
Deliver the ISTR as a .zip (similar to the initial state the Linda shared)

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#134]
The ISTR indicator is still not in the package. 

Typically this would first be discussed during sprint planning but that may be too late to benefit from the little time that Lyanne and Linda have. So @Tilmon I'll go ahead share my wish list here :-). Feel free to make suggest otherwhise.

* @Lyanneho it would be great if you have time to follow up on our latest emails.

* @lindadelacombaz you'll see other issues about PSTR but those I can do myself more easily. So I would prioritize supporting Lyanne since the code in ISTR is similar to PSTR. BTW I assign this to you only because I know you follow GitHub notifications -- and I'm not certain if that's the case for Lyanne.

**Comment by Tilmon** [comment]
Hi @maurolepore just seeing this now but to confirm: @Lyanneho and I talked this morning and she agreed to continue working on the ISTR today. Let's discuss next steps in the tech sprint if needed.
