### ISSUE TITLE
PCTR, ICTR, ISTR: create bar chart

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#138]
@Lyanneho , 

this task is to create barcharts that are aligned across indicators. Will share additional material and info later. 

You can use Linda's bar chart from a previous version for reference, see attached. In the folder README_files, you can find a bar chart from the PSTR for reference. 

Please adapt this to the PCTR and ICTR (and if time allows ISTR): 
The idea is that we create a barchart for each portfolio showing the total share of products in the different risk categories. This means in the case of the PCTR or ICTR, each grey box will be for a different co2-benchmark (all products, same sector, etc.) and each box should contain 1 bar each for low, medium and high risk. 

If you don't want to use Linda's draft 1:1 that's completely fine, pls feel free to re-design it completely. Don't set your creativitiy any limits! :) 

Thanks!

[tilt.transition.risk.mvp-main.zip](https://github.com/2DegreesInvesting/tiltIndicator/files/11253088/tilt.transition.risk.mvp-main.zip)

**Comment by maurolepore** [comment]
Closing for now. This is beyond of the scope of the next delivery and likely out of the scope of this package. 
A better place would be https://github.com/2DegreesInvesting/tiltPlot
