### ISSUE TITLE
In PSTR update the example datasets to use the new structure

### ISSUE THREAD

**Issue by lindadelacombaz** [2DegreesInvesting/tiltIndicator#155]
This is regarding [the conversation](https://github.com/2DegreesInvesting/tiltIndicator/pull/148#discussion_r1171174202) @Tilmon , @maurolepore and myself had on the companies id and number of products per companies.

A better test data set will be provided by @Tilmon.
Change the pstr indicator accordingly.

**Comment by maurolepore** [comment]
@lindadelacombaz, 

Tilman shared the new PSTR data [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/160) and I think that's an example dataset. Maybe you can pick a few rows and columns from it?

**Comment by maurolepore** [comment]
Relates to #160
