### ISSUE TITLE
In PSTR update the functions to work with the new data

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#160]
Dear @maurolepore , 

please find the zip file of the R project for data prep [data_prep_v1.zip in this folder](https://drive.google.com/drive/u/0/folders/1C0hffilt42OoJRAc6YENT7oH4YJwFlXM).

 Please note the following: 

- all data for pstr and pctr are in the folder "pstr_pctr_data". I did not yet remove all other files from that folder, so pls only consider those that start with pstr_ or pctr_. 
- The datasets pctr_companies and pctr_ecoinvent_co2 are in the exact same format as in the mvp
- The datasets for the pstr vary slightly as follows: 
    - pstr_companies already contains the matched scenario sectors. However, as you will see, there are 8 columns at the end containing scenario sectors, while it actually should only be 4. I didn't know how to "merge" them. If you know how to do that, please tell me :) 
    - pstr_ipr_2022 and pstr_weo_2022 replace pstr_weo_2022
    - pstr_ep_weo is not required anymore, as I already mapped the data directly into pstr_companies

Therefore, I imagine the following things need to be done: 

- [ ] merge the 8 scenario columns in pstr_companies into 4 as outlined above
- [ ] adapt the code so that it shows output for all 4 scenarios except for only one

I hope this is useful and will help you to work your way through the pstr indicator. Let me know if you have any questions. 

Good luck!

**Comment by maurolepore** [comment]
Dear @lindadelacombaz, 

It would be great if you could take over this issue. We can discuss on the tech sync but it seems clear from [this table](https://docs.google.com/spreadsheets/d/13RTGDMABUxSGJQkryZh4c1AoyXkqirUglhDD-N4XJw0/edit#gid=0) that this is of top priority.

In summary, the input data changed and we need to modify the PSTR indicator to input 2 datasets: `companies` and `scenario`. (Currently there are three inputs: `companies`, `ep_weo`, and `weo_2022`.)

TODO

- [ ] Update the example dataset
- [ ] Update the functions.
- [ ] Write basic tests.

Tilman and I drafted the new code in this #164. In that PR the top comment links to the rendered version of the .Rmd file we developed. You'll see a ["PSTR" section](https://github.com/2DegreesInvesting/tiltIndicator/blob/Use-real-data/data-raw/tmp/using-real-data.md#pstr) with the new functions. In short, we developed a new family of `pstr_prepare*()` functions that take the new input data and wrangle it to fit it in the existing `pstr_*()` functions -- except that `pstr_add_reductions()` had to be modified. 

Feel free to use the code as is or only as a reference to develop your own ideas.
