### ISSUE TITLE
T5 Adjust ranking benchmarks in ICTR & PCTR

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#167]
Dear @maurolepore and @kalashsinghal, 
 this is a ticket for a change in the PCTR & ICTR indicators. Maybe sth for @kalashsinghal to take over? 

PCTR & ICTR: The final indicators should have the following 6 benchmarks, please update accordingly: 
1) all 
2) all_&_unit 
3) tilt_sector 
4) tilt_sector_&_unit 
5) isic_4digit 
6) isic_4digit_&_unit 

If you prefer other names, feel free to adjust them.

**Comment by Tilmon** [comment]
Dear @kalashsinghal, the new inputd ata including isic & tilt sectors can be found here: https://drive.google.com/drive/folders/1aWemSm6D4Lqav0ff25vrcYvr97r2xXpr

**Comment by maurolepore** [comment]
FYI I removed a lot of duplication and exposed bencharmsk as the `.by` argument. I hope these changes will make this issue easier to implement.
