### ISSUE TITLE
Calculate each indicator with full, real data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#184]
Most likely we'll saturate the computer memory. We need to face this problem quickly so develop a strategy to manage it -- for example iterate over chunks of companies and over each scenario.

- [ ] ICTR
- [ ] ISTR
- [ ] PCTR
- [ ] PSTR

(As of today the only two indicators that work with the new data are ICTR and PCTR. Start with those first)

**Comment by Tilmon** [comment]
@maurolepore thanks for pointing this out. Question: How shall we approach calculating indicators on a larger scale and also in practice with the banks? I would imagine the following procedure:

1. We calculate all indicators for all companies in the tilt database
2. We share with banks the data for all companies in the relevant countries
3. We let banks select the relevant companies, e.g. by doing a join.  

Another approach could be to only calculate indicators for the relevant companies in banks' portfolios. But this would require them to apply the R code themselves. 

What do you think? Shall I test-run the indicators on all tilt companies?

**Comment by maurolepore** [comment]
So far we've always considered calculating the indicators ourselves. For our code to be ready for externals we need a lot more work. That limits our options to 1 or 2. It seems that 2 is easy enough (just subset the data for the countries relevant to a bank).

**Comment by Tilmon** [comment]
Ok cool, then we are on the same page. I was confused by the title but now it's clear. I'll test run the indicators with "all" real data that we have.

**Comment by maurolepore** [comment]
A note to self: This is currently blocked because we still don't have all the products. Mirja and Bob will deliver this.

**Comment by Tilmon** [comment]
**Update**: matching results of ep_products will be ready EOD today, see this ticket: [Finish ep_product matching and provide output table#26](https://github.com/2DegreesInvesting/NLPTiltMatch/issues/26)
Please note that matching of ep_activities will still take until Friday. As there are companies that have both ep_products and ep_activities, we need to wait with company-level bulk calculations until we have all data. What I suggest we can already do: 

- test how we can run bulk calculations without letting the computer crash (i.e. applying indicator code to ep_product matching output data once we have them)
- calculate product-level results with ep_product matching outputs (approx. 15k `clustered`) data that we already have by today EOD. 
- calculate product-level results with ep_activity matching outputs (approx. 2k `clustered`) data on Friday 
- calculating company-level results altogether afterwards

**Comment by maurolepore** [comment]
Closing because Tilman is doing it and will surely not forget :-)
