### ISSUE TITLE
In PCTR output `share_sector`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#191]
``` r
library(dplyr, warn.conflicts = FALSE)
library(tiltIndicator)

pctr_ecoinvent_co2 |>
  pctr_score_activities() |>
  pctr_score_companies(pctr_companies) |> 
  names()
#> [1] "company_id"     "score"          "share_all"      "share_unit"    
#> [5] "share_unit_sec"

ictr_inputs |>
  ictr_score_inputs() |>
  ictr_score_companies(ictr_companies) |> 
  names()
#> [1] "company_id"     "score"          "share_all"      "share_unit"    
#> [5] "share_sector"   "share_unit_sec"
```

<sup>Created on 2023-04-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by maurolepore** [comment]
@Tilmon note PCTR lacks `share_sector`. Is this expected?

**Comment by Tilmon** [comment]
@maurolepore sorry for late reply. PCTR & ICTR should in the end all have the same 6 benchmarks which is captured in @kalashsinghal 's task [T5 Adjust ranking benchmarks in ICTR & PCTR#167](https://github.com/2DegreesInvesting/tiltIndicator/issues/167). I assume this is something to start working on next week after all the tests and right output table formats are ready?
