### ISSUE TITLE
In PSTR update indicator outputs as in the googlesheet-template

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#199]
Dear @maurolepore, 

@AnneSchoenauer and I finished the output table templates. Please find them in [this Google Sheet](https://docs.google.com/spreadsheets/d/1K1thTMRg-k4DSdJy-G1RFY0islOQk70ToU3zmCKmvHM/edit#gid=1258737772).

Please note the following: 

- Company level results can be found in tab "[company_level_results](https://docs.google.com/spreadsheets/d/1K1thTMRg-k4DSdJy-G1RFY0islOQk70ToU3zmCKmvHM/edit#gid=1258737772)". The results for PCTR & ICTR are in the exact same structure as well as the results for PSTR & ISTR. In the templates, each pair is actually shown in the same table. This is no requirement and we can just keep separate output tables for each of the 4 indicators. 
- product-level results can be found in the respective tabs PCTR, ICTR, PSTR, and ISTR. 
- A documentation of where the columns come from can be found in the tab "[column_names](https://docs.google.com/spreadsheets/d/1K1thTMRg-k4DSdJy-G1RFY0islOQk70ToU3zmCKmvHM/edit#gid=506195027)". The column marked as "tbc" in the documentation can be ignored for now - all already included as placeholder, however you prefer. THey have lower priority and we need to see if we will "fill them with life". 

Please note here that not all columns are already included in the prepped data that I shared with you. The documentation shows from which data source the missing columns need to be taken (see yellow-colored cells). Now the questions is: How to add the missing columns? 
1. Would you prefer me adding them to the prepped data? I can do that by tomorrow afternoon. 
2. Would you prefer to adding them as part of the indicator calculation? All columns can be joined by the unique IDs from tiltData and Ecoinvent. 
3. Would you prefer me / us adding the missing columns at the end, after indicators are calculated? Then the code would still remain rather clean with the minimum required columns. 

Let me know which way you would prefer! Thanks!!!!

**Comment by maurolepore** [comment]
Thanks @Tilmon,

Looks like you had a busy day :-)

RE: 

> How to add the missing columns?

By far "3". We can later develop code to help you prepare inputs and polish outputs. But first let's work on just calculating the indicators. 

I need your help to parse the vast amount of  information in that GoogleSheet. From all that I need only a few key elements. Maybe we can do that in a meeting? 

To make the most out of that meeting I'll try to explain here what I'm looking for. You may detect some problems with my thinking. If so we can also discuss that.

--

My goal is to find the minimum columns that preserve all data and express the results in the same way for all indicators. This will not only help process the output for all indicators in the same way, but also may reveal common processes in the code that might be centralized to make it easier to understand, debug, and maintain.

I'll try to express what I understand in the most general terms.

* All processes aim to calculate a "transition risk", apparently defined by one or more numeric values, and one or more categorical values (low, medium, high).

* All processes compute first at a granular level (e.g. product), then aggregate at a coarser level (i.e. company). Each level is uniquely identified by an "id" (e.g. `*uuid`, and `companies_id`).

So it seems that:

* Every output should have columns `id`, (transition risk) `value`, and (transition risk)  `category`. 

* Some outputs seem to need one or more columns to modify the transition risk `value` and `category`, e.g. `type`: "all", "unit", "unit_sec". Or the `type` modifier might be spread along multiple columns (current state).

Do you start to see the way I'm thinking?

**Comment by Tilmon** [comment]
Dear @maurolepore please find the updated real sample data in this [folder](https://drive.google.com/drive/folders/1aWemSm6D4Lqav0ff25vrcYvr97r2xXpr), incl. a README documenting which data are private and which are public. 
Please further note that the sub-folder "OLD" contains previous input data versions, eg. the one from Friday. I just realized this morning that there were still some 2 or 3 columns which names weren't completely aligned across indicator datasets and hence, I uploaded an updated version of the data with the prefix "230502_" in the folder. Except for the few column names I changed, everything is the same as in the data starting with "230428_" in the folder "OLD".

**Comment by maurolepore** [comment]
This is done for ICTR and PCTR. The other indicators are lower priority.
