### ISSUE TITLE
In ICTR & PCTR: remove duplication of code through a common function

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#201]
@maurolepore FYI: I will add more info in this issue regarding which functions I will remove the duplicates from.

**Comment by maurolepore** [comment]
Note a lot of the duplication between ICTR and PCTR is gone via the common `xctr*()` functions. You may use that as inspiration for how to remove the remaining duplication.

**Comment by maurolepore** [comment]
This is happening organically
