### ISSUE TITLE
Do  2dii.* packages have anything  we can reuse?

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#203]
### Discussed in https://github.com/2DegreesInvesting/tiltIndicator/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **maurolepore** April 16, 2023</sup>
The package tilt.company.match overlapped with [r2dii.match](https://rmi-pacta.github.io/r2dii.match) but didn't use it -- except for one feature. That was surprising to @AnneSchoenauer and @Tilmon so I better remind you here again.

Do 2dii.* packages have anything useful for tiltIndicator?

For example:

1. Is there anything useful in [r2dii.data]( https://rmi-pacta.github.io/r2dii.data/reference/index.html)? Maybe WEO data?

``` r
r2dii.data::region_isos |> tail()
#>             region isos   source
#> 5920        brazil   br weo_2020
#> 5921         india   in weo_2020
#> 5922         japan   jp weo_2020
#> 5923        russia   ru weo_2020
#> 5924  south africa   za weo_2020
#> 5925 united states   us weo_2020

r2dii.data::region_isos |> head()
#>               region isos   source
#> 1 advanced economies   bg weo_2019
#> 2 advanced economies   hr weo_2019
#> 3 advanced economies   cy weo_2019
#> 4 advanced economies   mt weo_2019
#> 5 advanced economies   ro weo_2019
#> 6 advanced economies   au weo_2019
```

4. Is there any useful calculation or idea in [r2dii.analysis](https://rmi-pacta.github.io/r2dii.analysis/index.html)?

5. Is there any useful plot or idea for a plot in [r2dii.plot](https://rmi-pacta.github.io/r2dii.plot/index.html)?

</div>

**Comment by kalashsinghal** [comment]
Hi @Tilmon, Please close this issue if not relevant!
