### ISSUE TITLE
Remove duplication

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#212]
Dear @maurolepore and @kalashsinghal, 

please add details if needed.

**Comment by maurolepore** [comment]
Note ~1/2 of the job is already done. [All 4 indicators use `xctr_at_company_level()`](https://github.com/2DegreesInvesting/tiltIndicator/blob/0812197e3184d06104cdaa0186e9b022fa40ab41/R/pstr.R#L38). So the effort is focused on the product-level code.

**Comment by maurolepore** [comment]
The last several PRs removed as much duplication as I could. I'll close now so that re-writing ISTR has an issue of its own.
