### ISSUE TITLE
In PSTR update example datasets

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#231]
This comment by Tilman wasn't fully implemented ([confirmation](https://2investinginitiative.slack.com/archives/C050VAQACC9/p1683220246844919?thread_ts=1682671284.043449&cid=C050VAQACC9)). The reprex below shows that some of the columns he mentions don't exist in any of the example datasets.

Late April

> please find all input data for the indicators in the folder [02_input_data](https://drive.google.com/drive/folders/1aWemSm6D4Lqav0ff25vrcYvr97r2xXpr). ... Now, we have for all indicators the column `clustered` and the unique `company_id`, `activity_uuid_product_uuid` and `input_activity_uuid_product_uuid`. The newest files have today's date as a prefix (230428_).

Early May: See #199 

``` r
devtools::load_all()
#> ℹ Loading tiltIndicator
packageVersion("tiltIndicator")
#> [1] '0.0.0.9037'

find_dataset_with_columns_matching <- function(pattern) {
  datasets <- data(package = "tiltIndicator")[["results"]][, "Item"]
  out <- datasets |>
    lapply(get) |>
    setNames(datasets) |>
    sapply(\(.data) any(grep(pattern, names(.data))))
  names(out[out])
}

find_dataset_with_columns_matching(pattern = "activity_uuid_product_uuid")
#> [1] "ictr_companies"     "ictr_inputs"        "pctr_companies"    
#> [4] "pctr_ecoinvent_co2"

find_dataset_with_columns_matching(pattern = "input_uuid")
#> character(0)

find_dataset_with_columns_matching(pattern = "cluster")
#> [1] "istr_companies"
```

<sup>Created on 2023-05-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kalashsinghal** [comment]
@maurolepore After the changes in #237 the output of your reprex looks like this: 
``` r
devtools::load_all()
#> ℹ Loading tiltIndicator
packageVersion("tiltIndicator")
#> [1] '0.0.0.9038'

find_dataset_with_columns_matching <- function(pattern) {
  datasets <- data(package = "tiltIndicator")[["results"]][, "Item"]
  out <- datasets |>
    lapply(get) |>
    setNames(datasets) |>
    sapply(\(.data) any(grep(pattern, names(.data))))
  names(out[out])
}

find_dataset_with_columns_matching(pattern = "activity_uuid_product_uuid")
#> [1] "ictr_companies"     "ictr_inputs"        "pctr_companies"    
#> [4] "pctr_ecoinvent_co2"

find_dataset_with_columns_matching(pattern = "input_activity_uuid")
#> [1] "ictr_inputs"

find_dataset_with_columns_matching(pattern = "cluster")
#> [1] "ictr_companies" "istr_companies" "pctr_companies"
```

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by maurolepore** [comment]
@lindadelacombaz could you please update the example datasets for PSTR?
