### ISSUE TITLE
In PSTR thresholds should range 0-1 not 0-100 (and likely be the same as in XCTR: 1/3, 2/3)

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#281]
Relates to #212 
By making the interfaces identical, we make it easier to reuse code.

**Comment by maurolepore** [comment]
cc @Tilmon ?

**Comment by Tilmon** [comment]
@maurolepore @kalashsinghal please note the following that we just discussed: 

- thresholds for 2050 are 1/3 and 2/3
- thresholds for 2030 are 1/9 and 2/9

This can already be implemented manually as I understand.
