### ISSUE TITLE
Run ICTR on company- and product-level

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#289]
@kalashsinghal , 

please run ICTR and save company- and product-level results here: [https://drive.google.com/drive/u/0/folders/15lJ7tfH0KRB4mU0us7XUTBvpuo3MzxRU](https://drive.google.com/drive/u/0/folders/15lJ7tfH0KRB4mU0us7XUTBvpuo3MzxRU)

Use @maurolepore article on ["handling a long runtime"](https://2degreesinvesting.github.io/tiltIndicator/articles/handling-long-runtime.html).

**Comment by maurolepore** [comment]
I think this is done, so I'll close it. 
FYI @kalashsinghal
