### ISSUE TITLE
In PSTR, `reductions = NA` now yields an error (as `co2*` in XCTR)

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#296]
Before `NA` in `reductions` yielded "no_sector" in `risk_category`. But now I'm implementing the requirement that each company in each level of `grouped_by` must have risk categories "low", "medium", and "high". Also in XCTR it's a requirement that the column holding co2 values can't have missing values so NA's there trigger an error.

It seems to me that the column `reductions` is similar to `co2_footprint` as both hold some kind of co2 information that influences our risk-categories. So for consistency I believe the behaviour should be an  (option 3 bleow).

1. Before: yelds "no_sector".
2. Now: Yields "low", "medium", "high".
3. Should be an error (as in `xctr*()` with `NA`s in `co2_footprint`).

Do you agree? Or argue for another option?

### Now

``` r
library(tibble)
devtools::load_all()
#> ℹ Loading tiltIndicator
packageVersion("tiltIndicator")
#> [1] '0.0.0.9051'

scenarios <- tibble(
  reductions = NA,
  scenario = "1.5c required policy scenario",
  sector = "total",
  subsector = "energy",
  year = 2020,
  type = "ipr",
)

companies <- tibble(
  company_id = "a",
  type = "ipr",
  sector = "total",
  subsector = "energy",
)

pstr(companies, scenarios)
#> Error in `check_has_no_na()` at tiltIndicator/R/pstr.R:44:2:
#> ! The column 'reductions' can't have missing values.
#> ℹ Remove them with `dplyr::filter(data, !is.na(reductions))`.
```

### Before

``` r
library(tibble)
library(tiltIndicator)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9050'

scenarios <- tibble(
  reductions = NA,
  scenario = "1.5c required policy scenario",
  sector = "total",
  subsector = "energy",
  year = 2020,
  type = "ipr",
)

companies <- tibble(
  company_id = "a",
  type = "ipr",
  sector = "total",
  subsector = "energy",
)

pstr(companies, scenarios)
#> # A tibble: 1 × 6
#>   companies_id grouped_by                     risk_category value scenario  year
#>   <chr>        <chr>                          <chr>         <dbl> <chr>    <dbl>
#> 1 a            1.5c required policy scenario… no_sector         1 1.5c re…  2020
```

**Comment by Tilmon** [comment]
Hi @maurolepore thanks for exposing this. 

In contrast to XCTR, with PSTR I assume it to be more likely to have `NA` in `reductions`. Therefore, I would prefer to not yield an error but instead: 

- at product level: `risk_category `should be `NA`, as we simply cannot assign any risk category
- at company level: `risk_category` should have "low", "medium", "high" for each company. But the products with `NA `should be ignored from the `value `calculation. 

Is that feasible? 

If this is a bit of an overkill at this stage, please proceed with your suggested option 3 "Should be an error (as in xctr*() with NAs in co2_footprint" and put my suggested solution down in a ticket for future enhancements. 

Thanks!
