### ISSUE TITLE
Status & last adjustments to output tables

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#301]
FYI @AnneSchoenauer 

Folder with output files: https://drive.google.com/drive/u/0/folders/1QymvF6FdL7Wv4rP-A9iF0xQOqw67PzEu 

Following adjustments still need to be done: 

**Output files**

- [x] produce output files of PCTR on product- and company-level 
- [x] include `company_city`, `postcode`, `address` in both product- and company-level output files
- [x] include `reference_product` in product-level output file
- [x] find out whether we are allowed to share input data
- [x] delete `co2_column ` from output
- [x] move all IDs to the end
- [x] run output prep on ICTR product- and company-level
- [x] companies with no results should only have 1 empty row --> to be discussed
- [x] in ICTR, delete `input_activity_uuid_product_uuid` and remove duplicate rows
- [x] test whether `companies_id` align
- [x] re-order columns: companies_id, company_id, country, *CTR_share, risk_category, benchmarks, and then all others
- [x] share PSTR input data with Mauro
- [x] change 1 in output prep: delete multi_match == TRUE from ictr results
- [x] change 2 in output prep: adapt ep_ei_mapper so that it also has multiple IDs in one cell if multi_match == TRUE
- [x] change 3 in output prep: make sure that multi_match == TRUE in PCTR in some cases at least
- [x] run PSTR once ready
- [x] adjust output structure of PSTR

**Data prep**
- [x] make sure matching of `companies `and `products` files work also for multiple matches --> detect why it doesn't work right now (right now the output files shows multiple `activity_uuid_product_uuid `in those cases but all other relevant columns are empty.
- [x] update sector mappers 
- [x] re-run `tr_companies ` dataset once sector-mapper ready
- [x] update postcodes

**After all changes**

PCTR
- [x] update input data prep (sector mappers & matching bug)
- [x] run PCTR @kalashsinghal 
- [x] prepare output data @Tilmon 

ICTR
- [x] update input data prep (sector mappers & matching bug)
- [x] run ICTR @kalashsinghal 
- [x] prepare output data @Tilmon 

PSTR
- [x] update input data prep (sector mappers & matching bug)
- [x] run PSTR @maurolepore 
- [x] prepare output data @Tilmon

**Comment by AnneSchoenauer** [comment]
Hi Tilman, 
here my other comments (complemented to what you already wrote above): 
PCTR - company-level: 
- [ ] Can we inlcude any information in the pctr_company_level file of what the company does? So main activity for example? (Low priority)
- [ ] If I convert it to xls my company_names look really weird. For example: "ï»¿mathias maschinenhandel & laserservice" - are those names exactly the same names that we already shared with them before? There are also many values like '#NAME? for IDs and company - we shouldn't share it like this! [high priority]
- [ ] The benchmark compared with all and with unit should be calles "all_unit" [medium]
- [ ] There are no countries included which makes it hard if we just want to share the Netherlands with the Netherland banks for example - so lets include also "country" [high]
- [ ] I thought that Mauro, Kalash and Yana might have fixed the issue with some of the Netherland postcodes? For example for this company the postcode is "2522lr den haag". It should only be "2522" [medium]
- [ ] The Umlaute are not shown properly, e.g. "bÃ¼rgerplatz 12 | 80807 mÃ¼nchen" or "1 kfÃ© l'addition"
- [ ] Are there any companies missing? We have in total about 280,000 companies. And we know that we have per company 18 risk cateogries. Therefore, we would need a datasheet which has about 5,1 Mio. rows. The data sheet has only 1 Mio.?

**Comment by AnneSchoenauer** [comment]
PCTR - product- level

- [ ] I get the warning message "The large is too large to open in an xls grid" - does this matter? Did we discuss how to share the files with the banks as they are quite huge? (also for PCTR - company-level) [high]

**Comment by Tilmon** [comment]
@AnneSchoenauer you can find an updated version of both files in the linked folder (file names contain prefix _v2). 
A few comments: 

1. company names look weird in xlsx: That seems to be a conversion issue, the name in R is simply "mathias maschinenhandel & laserservice". We should investigate which xlsx setup we need to solve conversion issues. I can ask someone in Deloitte's team in the standup if they have time. Same for Umlaute. 
2. Warning message: The files seem indeed to be too large for Excel. That's apparently why you only see 1,000,000 rows instead of the 5.2 mln rows in the csv company-level results file. That is not very user-friendly. Let's think about work arounds. One could be: We ask users to share the `companies_id `with us for which they want results and then we only share a subset of results with them? Otherwise, they need to open the file in R to be able to see evreything. What do you think? 
3. `matching_certainty_average `: average of `matching_certainty `per company. For that I first translated risk_categories into numerical values, averaged them, and then back to risk_categories. Pls see the code below for details and let me know if you have questions. 

```{r}
pctr_product_level_4 <- pctr_product_level_3 |> 
  left_join(select(mapper_ep_ei, c(
    "country", "main_activity", "clustered", "activity_uuid_product_uuid", "multi_match", "completion")), 
            by = c("country", "main_activity", "clustered", "activity_uuid_product_uuid")) |> 
  rename(matching_certainty = completion) |>
  mutate(matching_certainty_num = case_when(
    matching_certainty == "low" ~ 0, 
    matching_certainty == "medium" ~ 0.5, 
    matching_certainty == "high" ~ 1, 

  ))

# create new column with company-level averages for matching_certainty
pctr_product_level_5 <- pctr_product_level_4 |> 
  group_by(companies_id) |>
  mutate(avg_matching_certainty_num = mean(matching_certainty_num, na.rm = TRUE)) |> 
  ungroup()

# create column with "low", "medium", "high" values for company averages
pctr_product_level_6 <- pctr_product_level_5 |> 
    mutate(avg_matching_certainty = ifelse(
    avg_matching_certainty_num > 2/3, "high",
    ifelse(avg_matching_certainty_num > 1/3, "medium", "low")
  ))  
``` {r}
