### ISSUE TITLE
Run PSTR with real data

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#312]
Dear @maurolepore , 

as discussed, please try to run the PSTR with real data and produce company- and product-level results. 

You can find the input data here (3 files starting with str_): https://drive.google.com/drive/u/0/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP 

If you successfully manage to calculate the outputs, please store them here as zip: https://drive.google.com/drive/u/0/folders/1QymvF6FdL7Wv4rP-A9iF0xQOqw67PzEu 

Thank you!

**Comment by Tilmon** [comment]
@maurolepore pls note I updated the link for the input data because I moved the input data to another folder where they are supposed to be.

**Comment by maurolepore** [comment]
PSTR is still running. I uploaded what I got so far. I used the prefix `WIP_` to reflect it's work in progress. It's running at about 80K companies per hour. I'll go sleep and expect it to be done by the time I check in around your noon-ish. 

Overall, it took me a long time to run `pstr_prepare*()` . The code I used is [here](https://gist.github.com/maurolepore/c73ae7e476798784cfe4520c1cbeb5e9). You'll see a number of FIXME and hacks around them.  I'm not sure what's running is useful so please spend some time inspecting it.

**Comment by Tilmon** [comment]
@kalashsinghal can you pls check out the code and data that @maurolepore produced and let me/us know whether you spotted anything unexpected? I'll also try to have a look later, but can't promise atm.

**Comment by maurolepore** [comment]
@AnneSchoenauer said

> If you look at this sheet https://docs.google.com/spreadsheets/d/1ViTkhidRxcMLqlakH9oN4POT2RvTP0mCDm2yoi1TCU4/edit you see that there are NAs for the land use sector. This shouldn’t be the case as the land use sector should be covered by the IPR scenarios. However, maybe I am missing something here and tilman knows why this is the case. I would suggest that you create the rest of the outputs if you have the time today and wait what Tilman says on Monday. If you already see that this is a technical problem you might resolve it but as I said I think it is more content related.

**Comment by maurolepore** [comment]
FYI the PSTR outputs are already uploaded. See the files `pstr_product_level.zip` and `pstr_company_level.zip`  [here](https://drive.google.com/drive/u/0/folders/1QymvF6FdL7Wv4rP-A9iF0xQOqw67PzEu). Each .zip contains a single .csv.
