### ISSUE TITLE
Run PCTR & ICTR with all real data

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#313]
Dear @kalashsinghal , 

as discussed, please re-run the PCTR & ICTR indicator on product- and company-level. 

You can find the new input data here: https://drive.google.com/drive/u/0/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP 

Pls store the output data here: https://drive.google.com/drive/u/0/folders/1QymvF6FdL7Wv4rP-A9iF0xQOqw67PzEu 

Thank you!

cc' @maurolepore

**Comment by kalashsinghal** [comment]
Dear @Tilmon, 

I stored the output of ICTR and PCTR's real input data in this [folder](https://drive.google.com/drive/u/0/folders/1QymvF6FdL7Wv4rP-A9iF0xQOqw67PzEu). Therefore, I am closing this issue.
