### ISSUE TITLE
NAs and no_sectors in risk_category of PSTR

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#316]
Dear @Tilmon and dear @maurolepore, 
I randomly checked now some companies and I noticed one issue which I however don't know if it is on purpose, if it is a technicality or if is content-related. Therefore, @maurolepore if you don't see that it is a code problem, I am afraid that we need to wait for @Tilmon to tell us what he thinks about the issue on Monday. 
I noticed that some of the companies don't have any sector and therefore land in the risk category "no_sector". However in this sample company [here](https://docs.google.com/spreadsheets/d/1ViTkhidRxcMLqlakH9oN4POT2RvTP0mCDm2yoi1TCU4/edit#gid=975827873), we should have sectors namely the "Land Use" sector that should be matched with a sector reduction target of IPR. I didn't check if now all "Land Use" sectors are not matched to a scenario - so I don't know if the sample company is an excemption but this is, so far as I know, not correct. 
Other than that the outputs are great and look exactly of how we would like to see them. 
@maurolepore if you are nearly there with running the whole PSTR I would suggest that you continue to finish the outputs. So that if this issue here is not a real issue, @Tilmon can work with the output tables on Monday. 
Thanks both!

**Comment by maurolepore** [comment]
@AnneSchoenauer there an issue for this. I'll close this one and continue there.

https://github.com/2DegreesInvesting/tiltIndicator/issues/315
