### ISSUE TITLE
Review PCTR & ICTR final outputs that we want to share with banks

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#318]
Dear @kalashsinghal , 

please review the final outputs that we want to share with banks today and reach out if you see any unexptected output. Outputs can be accessed here: https://drive.google.com/drive/folders/1nTdJNIyCrMMGrH2uIFkYs6zyR2ZKeBwr 

Thank you!

**Comment by maurolepore** [comment]
Is this still open?

**Comment by maurolepore** [comment]
I see it's labeled as "Done" so I'll go ahead and close it.
