### ISSUE TITLE
Re-run PCTR & ICTR on company- and product-level

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#319]
Dear @kalashsinghal , 

please re-run the PCTR & ICTR with the updated datasets 

- pctr_products_v2.csv
- ictr_products_v2.csv

Company dataset tr_companies.csv is still the same. 

Data to be found in this folder: https://drive.google.com/drive/u/0/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP

Pls upload results with _v2 in name here: https://drive.google.com/drive/u/0/folders/1QymvF6FdL7Wv4rP-A9iF0xQOqw67PzEu

**Comment by kalashsinghal** [comment]
@Tilmon closing this issue as the work is completed
