### ISSUE TITLE
In ISTR update example data and code

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#347]
We need to be able to compute ISTR. The best way it to reuse code in other indicators, so that the bugs we fixed for other indicators will automatically carry over to ISTR.

A great way to go about this is to copy and adapt -- one by one -- the tests we already have for other indicators. We can start by adding all the tests that pass without any change in the code, then working with the ones that don't pass and require some change in the code -- which will be safe if we already have the "easy" tests.

Most code is already done: The code at company level is identical for all indicators, so the only code that needs work is at product level. And within that, the core is mostly done too. 

What's still outdated is the code closer to the inputs and outputs.  The inputs are outdated. We need to check with @Tilmon what's the latest input data for ISTR and adapt the example datasets accordingly. And the outputs also need work because some of what we expect to output doesn't still exist in the example inputs.

**Comment by kalashsinghal** [comment]
> @kalashsinghal FYI I updated ticket description with link to datasets (from our discussion in Slack)

Thanks @Tilmon for updating the description!
