### ISSUE TITLE
In *CTR and *STR documentation, update thresholds

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#351]
Dear @lindadelacombaz , 

you spotted that thresholds in the documentation for the indicators do not align with the actual default thresholds in the indicator code. Please update the documentation accordingly. This has low priority, as we did not share the code and documentation with banks yet.

**Comment by lindadelacombaz** [comment]
@Tilmon, @maurolepore - FIY : Here is [my draft PR ](https://github.com/2DegreesInvesting/tiltIndicator/pull/352) regarding this ticket - I'll have to merge the other draft PR one first before this one because I have commits from the other branchs in my PR.
