### ISSUE TITLE
In *STR output tables, divide `grouped_by` into `scenario` and `year`

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#355]
Dear @kalashsinghal , 

I feel like we already talked about this in last week's sprint but I can't find a related ticket. Please add columns `scenario `and `year` in all *STR output tables in addtition to `grouped_by`.

Thanks!

cc' @lindadelacombaz and @maurolepore

**Comment by maurolepore** [comment]
See [`xstr_polish_output_at_company_level()`](https://2degreesinvesting.github.io/tiltIndicator/reference/xstr_polish_output_at_company_level.html#ref-examples).

**Comment by kalashsinghal** [comment]
> I feel like we already talked about this in last week's sprint but I can't find a related ticket. Please add columns `scenario `and `year` in all *STR output tables in addtition to `grouped_by`.

@maurolepore Tilman also want the `grouped_by` column in addition to the splited `scenario` and `year` columns. Hence, I am reopening this issue to do a slight modification to the `xstr_polish_output_at_company_level()` function.

**Comment by Tilmon** [comment]
@kalashsinghal @maurolepore I don't mind about the `grouped_by` column. I thought that column is important for you because it is the same as in XCTR. But for the output we share with banks I only need `scenario `and `year`. So whether you keep `grouped_by `or not, is up to you

**Comment by kalashsinghal** [comment]
@maurolepore @Tilmon I am closing this issue because `group_by` column is not required at the output level.
