### ISSUE TITLE
Develop a helper to prune XSTR `companies` in a way that maximizes the sector information we retain

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#356]
UPDATE [May 26, 2023] 

Hi Kalash, you can find the new data here: https://drive.google.com/drive/u/0/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP

There is one more step in the company dataset preparation that needs to be done. I didn't really know how to do it the best way, so I hope you can take it over. What we want is the following: 

If a company has NA in clustered and activity_uuid_product_uuid delete the row only if the tilt_sector in that row exists already in at least one other row of the company with a clustered & activity_uuid_product_uuid value. Otherwise, keep it. The reason for that is: We want to utilize as many sector info per company as possible. I.e. even if a row without a product has a sector that's not captured by the other products of the company, we want to keep that row. If that sector of the empty row is already captured by products, we do not want to keep it to not introduce unnecessary duplications. 

Example dataset is shown here: https://docs.google.com/spreadsheets/d/1REpvE4F2MypAi8OyfUA9JbH-sQC-z08s6mVzssjhHbM/edit#gid=0 

UPDATE [May 31, 2023]
`str_companies `is now called `pstr_companies `as we use two distinct companies datasets for PSTR (pstr_companies) and ISTR (istr_companies). I renamed the file names in our Google Drive [here](https://drive.google.com/drive/u/0/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP).

**Comment by kalashsinghal** [comment]
Dear @Tilmon 

Here is the code I used to update the `str_companis.csv` dataset based on the final example dataset:

``` r
devtools::load_all()
#> ℹ Loading tiltIndicator
library(dplyr)
library(here)
#> here() starts at /Users/kalashsinghal/git/2DII/tiltIndicator
packageVersion("tiltIndicator")
#> [1] '0.0.0.9063'
companies1 <- companies |>
  select(companies_id, clustered, activity_uuid_product_uuid, tilt_sector) |>
  slice(19:26)
companies1
#> # A tibble: 8 × 4
#>   companies_id                      clustered activity_uuid_produc…¹ tilt_sector
#>   <chr>                             <chr>     <chr>                  <chr>      
#> 1 07-schanksysteme-gmbh_0000000507… drinks, … 09516d9a-bf2d-558a-b4… non-metall…
#> 2 07-schanksysteme-gmbh_0000000507… refriger… 9649930d-2cc8-510f-88… non-metall…
#> 3 07-schanksysteme-gmbh_0000000507… <NA>      <NA>                   other; lan…
#> 4 07-vins_fra782708-00101           beverages e135b4f8-1a47-56fe-a4… non-metall…
#> 5 07-vins_fra782708-00101           <NA>      <NA>                   land use   
#> 6 0700showstarde-inh-harry-fox_000… meat      5146da88-501c-54f8-97… land use   
#> 7 0700showstarde-inh-harry-fox_000… meat, pr… 5146da88-501c-54f8-97… land use   
#> 8 0700showstarde-inh-harry-fox_000… <NA>      <NA>                   land use   
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid

# Case 3 doesn't exist in the dataset because `duplicates` table is empty.
duplicates <- companies1 %>%
  filter(is.na(clustered) & is.na(activity_uuid_product_uuid)) %>%
  group_by(companies_id, tilt_sector) %>%
  filter(n()>1)
duplicates
#> # A tibble: 0 × 4
#> # Groups:   companies_id, tilt_sector [0]
#> # ℹ 4 variables: companies_id <chr>, clustered <chr>,
#> #   activity_uuid_product_uuid <chr>, tilt_sector <chr>

# Useful code for data preparation
# Created a separate dataframe for Case2 scenario, in which I have extracted rows with unique tilt sector and NAs (to be kept case)
data1 <- companies1 %>%
  group_by(companies_id, tilt_sector) %>%
  filter(n() == 1) %>%
  filter(is.na(clustered) & is.na(activity_uuid_product_uuid))
data1
#> # A tibble: 2 × 4
#> # Groups:   companies_id, tilt_sector [2]
#>   companies_id                      clustered activity_uuid_produc…¹ tilt_sector
#>   <chr>                             <chr>     <chr>                  <chr>      
#> 1 07-schanksysteme-gmbh_0000000507… <NA>      <NA>                   other; lan…
#> 2 07-vins_fra782708-00101           <NA>      <NA>                   land use   
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid
# Removed all the rows with NAs in the `clustered` and `activity_uuid_product_uuid` columns
data2 <- companies1 %>%
  filter(!is.na(clustered) & !is.na(activity_uuid_product_uuid))
data2
#> # A tibble: 5 × 4
#>   companies_id                      clustered activity_uuid_produc…¹ tilt_sector
#>   <chr>                             <chr>     <chr>                  <chr>      
#> 1 07-schanksysteme-gmbh_0000000507… drinks, … 09516d9a-bf2d-558a-b4… non-metall…
#> 2 07-schanksysteme-gmbh_0000000507… refriger… 9649930d-2cc8-510f-88… non-metall…
#> 3 07-vins_fra782708-00101           beverages e135b4f8-1a47-56fe-a4… non-metall…
#> 4 0700showstarde-inh-harry-fox_000… meat      5146da88-501c-54f8-97… land use   
#> 5 0700showstarde-inh-harry-fox_000… meat, pr… 5146da88-501c-54f8-97… land use   
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid

# Joined the data1 and data2 to get the final results
result <- rbind(data1, data2)
result
#> # A tibble: 7 × 4
#> # Groups:   companies_id, tilt_sector [6]
#>   companies_id                      clustered activity_uuid_produc…¹ tilt_sector
#>   <chr>                             <chr>     <chr>                  <chr>      
#> 1 07-schanksysteme-gmbh_0000000507… <NA>      <NA>                   other; lan…
#> 2 07-vins_fra782708-00101           <NA>      <NA>                   land use   
#> 3 07-schanksysteme-gmbh_0000000507… drinks, … 09516d9a-bf2d-558a-b4… non-metall…
#> 4 07-schanksysteme-gmbh_0000000507… refriger… 9649930d-2cc8-510f-88… non-metall…
#> 5 07-vins_fra782708-00101           beverages e135b4f8-1a47-56fe-a4… non-metall…
#> 6 0700showstarde-inh-harry-fox_000… meat      5146da88-501c-54f8-97… land use   
#> 7 0700showstarde-inh-harry-fox_000… meat, pr… 5146da88-501c-54f8-97… land use   
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid
```

<sup>Created on 2023-05-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Is it how the final companies dataset you expected to look like?

**Comment by Tilmon** [comment]
@kalashsinghal good stuff, that's what I expected the dataset to look like. Thank you!

**Comment by kalashsinghal** [comment]
Dear @Tilmon and @maurolepore 

I have uploaded a new file named `str_companies_final.csv.zip` after applying above data prep code to the whole `str_companies.csv` file in this [folder](https://drive.google.com/drive/u/0/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP). This new file can be used to re-run PSTR after Mauro's review on the changes made.

**Comment by maurolepore** [comment]
@kalashsinghal I think your approach works well. 

Here is my own attempt:

``` r
library(tidyverse)
options(width = 200)

add_is_to_keep <- function(data) {
  data |>
    group_by(companies_id, tilt_sector) |>
    mutate(is_odd = ifelse(is.na(clustered) & is.na(activity_uuid_product_uuid), TRUE, FALSE)) |>
    arrange(is_odd, .by_group = TRUE) |>
    mutate(is_odd_and_first = is_odd & row_number() == 1L) |>
    mutate(is_to_keep = case_when(
      !is_odd ~ TRUE,
      is_odd & is_odd_and_first ~ TRUE,
      .default = FALSE
    )) |>
    ungroup()
}

companies <- tibble::tribble(
  ~rowid, ~companies_id, ~clustered, ~activity_uuid_product_uuid, ~tilt_sector,
       1,           "a",       "b1",                        "c1",          "x", # keep
       2,           "a",         NA,                          NA,          "x", # drop
       3,           "a",         NA,                          NA,          "x", # drop

       4,           "a",         NA,                          NA,          "y", # keep
       5,           "a",         NA,                          NA,          "y", # drop"

       6,           "a",       "b6",                        "c6",          "z", # keep
       7,           "a",       "b7",                          NA,          "z", # keep
)

# Keep rowid 1, 4, 6, 7
companies |>
  add_is_to_keep() |>
  filter(is_to_keep)
#> # A tibble: 4 × 8
#>   rowid companies_id clustered activity_uuid_product_uuid tilt_sector is_odd is_odd_and_first is_to_keep
#>   <dbl> <chr>        <chr>     <chr>                      <chr>       <lgl>  <lgl>            <lgl>     
#> 1     1 a            b1        c1                         x           FALSE  FALSE            TRUE      
#> 2     4 a            <NA>      <NA>                       y           TRUE   TRUE             TRUE      
#> 3     6 a            b6        c6                         z           FALSE  FALSE            TRUE      
#> 4     7 a            b7        <NA>                       z           FALSE  FALSE            TRUE
```

<sup>Created on 2023-05-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Tilmon** [comment]
Dear @maurolepore and @kalashsinghal pls note that for clarity I added an update in the task description that explains that `str_companies `is now called `pstr_companies`. I leave it up to you to decide whether you want to re-name the dataset name in the title or not.

**Comment by kalashsinghal** [comment]
> @kalashsinghal I think your approach works well.
> 
> Here is my own attempt:
> 
> ```r
> library(tidyverse)
> options(width = 200)
> 
> add_is_to_keep <- function(data) {
>   data |>
>     group_by(companies_id, tilt_sector) |>
>     mutate(is_odd = ifelse(is.na(clustered) & is.na(activity_uuid_product_uuid), TRUE, FALSE)) |>
>     arrange(is_odd, .by_group = TRUE) |>
>     mutate(is_odd_and_first = is_odd & row_number() == 1L) |>
>     mutate(is_to_keep = case_when(
>       !is_odd ~ TRUE,
>       is_odd & is_odd_and_first ~ TRUE,
>       .default = FALSE
>     )) |>
>     ungroup()
> }

I think your approach is better because it counters Case 3 in a better way than mine. Therefore, please use your approach! Thanks!

**Comment by maurolepore** [comment]
@kalashsinghal thanks for your feedback.

@Tilmon, 

Can you please see the reprex in [this comment](https://github.com/2DegreesInvesting/tiltIndicator/issues/356#issuecomment-1569306283) and confirm this is what you want? In particular note the case of `rowid` 6 and 7 and confirm that you expect to treat them the same way as we treat `rowid` 1 -- i.e. that cases when only one of either `clustered` or `*uuid` are `NA` are treated the same way as we treat the case when none is `NA`.


NOTE I changed the title of this issue to focus on developing the code. I believe the issue of applying it to pre-processing steps before running tiltIndicator functions seems to be separate and instead belong to #312 and #363.

**Comment by Tilmon** [comment]
@maurolepore I confirm that what you show in the reprex is what I want, thanks! 

> In particular note the case of rowid 6 and 7 and confirm that you expect to treat them the same way as we treat rowid 1 -- i.e. that cases when only one of either clustered or *uuid are NA are treated the same way as we treat the case when none is NA.

Confirmed as well. Not sure if this case actually exists right now in the data, but if it does, the logic you applied is how I would want it to be.
