### ISSUE TITLE
Update the scenario datasets for ISTR and PSTR

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#388]
Scenario datasets `str_ipr_targets` and `str_weo_targets` must be updated from this source: https://drive.google.com/drive/folders/15AsbEhET2WvU0z2dFhyKfvZF9jQHPuvP

**Comment by Tilmon** [comment]
@kalashsinghal does this refer to an updated version without duplicated scenario rows? If so, I guess I need to provide you with the new scenario data. Therefore, I put this on "BLOCKED".
