### ISSUE TITLE
In PSTR, deduplicate outputs

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#392]
Hi @maurolepore , 

seems that both the `pstr_product_level `and `pstr_company_level `results contain duplicates. I checked the input data and they don't contain duplicates. Do you know where / why / how the duplicates were introduced? 

We can simply remove them in the output but I think it would be useful to udnerstand where they come from.

**Comment by maurolepore** [comment]
``` r
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
packageVersion("tiltIndicator")
#> [1] '0.0.0.9059'

options(readr.show_col_types = FALSE)

product <- read_csv("/mnt/pstr_product_level_v2.csv")
identical(product, distinct(product))
#> [1] FALSE

company <- read_csv("/mnt/pstr_company_level_v2.csv")
identical(company, distinct(company))
#> [1] FALSE
```

<sup>Created on 2023-06-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Tilmon** [comment]
Hi @maurolepore, OK, thanks for the info. I fixed it now in my output preparation script as follows: 
```{r}
pstr_product_level3 <- distinct(pstr_product_level2)
pstr_company_level2 <- distinct(pstr_company_level)
```
