### ISSUE TITLE
In XSTR at product level drop `NA`s in `risk_category` with `if_all_na_is_first_else_not_na()`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#399]
Relates to #393

Our recent checks of XSTR output show we need to discuss, implement, and test what to do with unmatched products (e.g. [this comment on slack](https://2investinginitiative.slack.com/archives/C050VAQACC9/p1685738155500889?thread_ts=1685707647.132039&cid=C050VAQACC9)).

A good guide might be this test in xctr, e.g. https://github.com/2DegreesInvesting/tiltIndicator/blob/42bb903c7c0bb6e88881ba3c818ecfd6b33c8a30/tests/testthat/test-xctr_at_product_level.R#L28

Note xctr uses `prune_unmatched_products()` but I recalled that didn't work for xstr. However, I don't know if the opposite would work -- i.e. if the implementation in xstr will also work in xctr.

Tilman confirmed we want the same behaviour for all indicators: For each company-result drop rows where `risk_category` is `NA` except for one row if all `risk_category` is `NA`.

See 

https://github.com/2DegreesInvesting/tiltIndicator/pull/397/files#r1223588593
https://github.com/2DegreesInvesting/tiltIndicator/pull/397/files#r1223589366

- [ ] Clarify if this is what we want by company and product rather than just by company. That is, if a company has a non-missing values of `risk_category` for product "a", do we still want a row for that company with `NA` in the unmatched product "b"?

**Comment by Tilmon** [comment]
@maurolepore changed name to XSTR

**Comment by Tilmon** [comment]
@maurolepore I can't delete my comment but I didn't change the title, that was just a mistake. 
Instead of changing the name, I'd like to add to the description: 
As it is for the *STR family, also in the *CTR family, NA rows should be dropped, but not whole companies should be removed. I.e., if a company has only NAs, please keep it with one row and make every other column `NA`.
