### ISSUE TITLE
Why there are `NAs` in `tilt_sector` if there is risk categorisation value for a product in PSTR product level output file?

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#408]
Problem can be visualised through this file: https://docs.google.com/spreadsheets/d/1YO3nP6j2W4_lcgY0XQdo6Ibr_l-4ZE_zdZtdFsUCKIE/edit#gid=1328635298

UPDATE [June 15, 2023]
BLOCKED as this needs to be solved during data prep re-factoring

**Comment by kalashsinghal** [comment]
@Tilmon I identified from `str_companies2.csv` dataset for PSTR, that `tilt_sector` and `tilt_subsector` have `NAs` but the `ipr` and `weo` sectors and subsectors don't have NAs. Hence, due to presence of scenario sector information in both companies and scenario datasets, we have a risk categorisation value for the ep_product `wires, electric`.

**Comment by Tilmon** [comment]
Closing this as not planned because it was not explicitly addressed, but it was solved as part of re-factoring data prep and re-running indicators.
