### ISSUE TITLE
Weighing loanbook

### ISSUE THREAD

**Issue by lindadelacombaz** [2DegreesInvesting/tiltIndicator#445]
(From Anne's email) 
Background : 
Banks give loans to companies which produce mostly more than one product. When matching our data (e.g. PCTR, product level) with loanbooks, we know how much many one bank gives to one company. However, we don't know for which product the company uses this money. So we don't know which of the products is financed by the company. For now we normally assume an equal weight. But that means that in some cases we are under estimating how much banks finance high risk products, and in some case we under estimate how much banks finance low products. Therefore, we need to develop some metrics/different approaches to mirror this uncertainty. 

Toy data set: 
I came up with [this toy dataset](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=0). You can see here one bank and 7 companies that all produce different products associated with different risks. Now, we have four different ways of weighing the loan financing different products. 
Approach a) "equal weight" - here we only divide the amount of the loan (1000 EUR) by the number of products of the company. 
Approach b) "worst-case" - here we weigh the loan as such that we assume that all money goes into the highest risk product. If there are two or more products associated with the same highest risk, we assume equal weights again. 
Approach c) "best-case" - similar to the worst-case scenario but just with the lowest-risk category. 
Approach d) "main-activity" - sometimes banks give one sector classification to one company. However, with our data we know that sometimes the products stem from different sectors. Knowing that the bank categorise the product in one specific sector, we could assume that the bank only finance the product in the sector that it categories the company in. 
You can also see in the XLS that if I use the function "sum-if" that each approach would come up with different results. 

Task: 
Could you please do the following. 

- Based on the toy data set, could you come up with rules/code to calculate automatically column E. 

- Based on the toy data set, could you come up with rules/code to calculate automatically column I-L. For example, column I is the pure calculation (column B/column E). For column J and K it is a bit more complicated. The rule must be that the code always picks the product with the highest risk category (column J) and if there are multiple products in this risk column divides again the amount of the loan by the number of distinct products in the highest risk category. Column K the other way around  (lowest risk category). Column L must be to allocate all money to the products that have the same tilt sector (column H) as the bank associated with the company (column D). Again, if there are many products with the same sector, the loan is divided into those products. 

- Could you come up with a code that captures the "sum_if" function that you can see in column I20-L22. 

- Would be great if you maybe first create an explorative code, which I could apply to the real data (I am preparing the data according to the toy data set). Once we checked on some edge cases, you could then make the code robust?

**Comment by AnneSchoenauer** [comment]
Hey Linda, I reviewed your code and already applied it! Thanks a lot for this! This is great! I am writing to you some feedback that I noticed:

1. Automatically calculate column "amount_of_distinct_products". My data is a bit more complicated as the toy data as we have also different banks lending to companies. Therefore, I added in the group_by function also (company_name, bank). With this it works fine! However, your test is not very suitable for me as I don't have an "original" toy data set. I thought maybe it is good to have the test to add all products together wihtout grouping them and then summarising all the groups. That means before calculating hte distinct amount you could sum all products. And then after using the funciton we are adding the grouped by together. It should be the same result right if the function works properly.
2. With the other functions and the tests it is the same. If you want to include tests, I would need some that work separately from the dataset that I gave you. However, maybe it is also fine not having any tests? What do you think?
3. Other than that it is top! Thanks a lot :leichtes_lächeln:
