### ISSUE TITLE
Explore ISTR issue: missing input for IPR scenario

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#454]
Hi @kalashsinghal , 

exploring your sample outputs for `istr_productresult.csv`, I realized the following: For the `companies_id` ferdinand-bidla-gesellschaft-mbh_aut005254-00101, the results for WEO show 3 inputs but for IPR only 2 inputs. Why is that so? I can't make sense out of it. I checked the sector mappers but can't find the source of the problem. Can you please investigate?

- `companies_id`: ferdinand-bidla-gesellschaft-mbh_aut005254-00101
- `input_name`: `waste mineral oil`, `lubricating oil`, `electricity, medium voltage`

Issue: `electricity, medium voltage` does not appear as result for IPR, only for WEO. 

Why?

**Comment by kalashsinghal** [comment]
@Tilmon This issue is resolved after updating the sector mappers. Therefore, I am closing this issue.
