### ISSUE TITLE
Sector mapper: `clustered_id` and therefore presumably `ep_products` in indicators don't have distinct `tilt_subsector`

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#472]
Dear @kalashsinghal and @bobresink, 

I noticed that the `clustered_id` of the sector data that Mirja used for the matching processes is not a distinct dataset, meaning that there are cases where one `clustered_id` (ep_product) has two different `tilt_subsectors`. This would be inconsistent. I don't know if this problem also exists for the XSTR  indicators but according to @Tilmon, Mirja was using this sector mapper for the matching process. Therefore, could you please check if this introduces an error in the indicator data? Again an error would be if one `clustered_id` that belongs to an `ep_product` would have two or more distinct `tilt_subsectors`. 

Here a summary of the data that were used: 
```
# Load dataset from https://github.com/2DegreesInvesting/tiltIndicator/issues/456
all_sectors <- read_csv(here("all_sectors_manual_changes.csv")

# identifying duplicated clustered_ids in all_sectors dataset. 
duplicated_values <- all_sectors %>%
  filter(duplicated(clustered_id) | duplicated(clustered_id, fromLast = TRUE))

# Result: All 55 duplicated clustered_id are in the approach "lca". Figure out where this comes from in Mirja's script that compiled the sectors. All information on the sector data from Mirja can be found here: https://2investinginitiative.slack.com/archives/C0466FTHNLE/p1689310316546809
# all_sectors_manual_changes.csv is just the row-bound combination of the two datasets that Mirja provided (incl. 2 manual changes labelled with approach "manual"). 
```
I also attached the csv file with the duplicates. [duplicated_clustered_id.csv](https://github.com/2DegreesInvesting/tiltIndicator/files/12195875/duplicated_clustered_id.csv)

Priority-wise: Could you please do this before the 25th of August? Thanks!

Let me know if this task is unclear and thanks for checking! 
All the best
Anne

**Comment by kalashsinghal** [comment]
Dear @AnneSchoenauer and @bobresink 

Please use this [link](https://github.com/2DegreesInvesting/NLPTiltMatch/blob/tilt_subsector_duplicates/1_data_selection_kalash.ipynb) to see that a single `ep_id` can have multiple `activity_uuid_product_uuids` which creates one-to-many mapping for `isic` and `tilt_subsectors`. This one-to-many mapping is causing the issue of more than one `tilt_subsector` for `ep_products`. Please let me know how I can help you guyz to resolve this issue further! Thanks!

**Comment by bobresink** [comment]
Dear @AnneSchoenauer and @kalashsinghal 

This issue would be resolved if that for one ep_id there should only be a single activity_uuid_product_uuid possible that it can be mapped to, which I think we should change in the methodology. @AnneSchoenauer lets discuss this next meeting.

**Comment by AnneSchoenauer** [comment]
I think it is best to do the following that I noted [here:](https://github.com/2DegreesInvesting/NLPTiltMatch/issues/34#issuecomment-1786778019)
