### ISSUE TITLE
Remove useless data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#531]
The README file of tiltIndicatorAfter says that it "cleans the usless data" from the output of tiltIndicator.

@kalashsinghal can you please help me identify that useless data so I can remove it from the tiltIndicaor, rather than passing it to tiltIndicatorAfter?

**Comment by kalashsinghal** [comment]
@maurolepore I didn't mean that the useless data is coming from tiltIndicator package. By useless data I meant the useless columns that were being created after joining the files like "ecoinvent_inputs" to the final outputs from tiltIndicator package. 

Although, the column `co2_footprint` coming from tiltIndicator package is used to create new column `avg_matching_certainty` in tiltIndicatorAfter package. After creating `avg_matching_certainty` column, `co2_footprint` column is to be removed from the tiltIndicator outputs. Hence, you might want to refactor/remove `co2_footprint` and `input_co2_footprint` columns to make code more robust.

**Comment by maurolepore** [comment]
Thanks! Much clearer now.
