### ISSUE TITLE
Give update on status of Sector Profile - Upstream

### ISSUE THREAD

**Issue by bobresink** [2DegreesInvesting/tiltIndicator#536]

**Comment by maurolepore** [comment]
You can see the current state at these links:

* [tiltIndicator](https://2degreesinvesting.github.io/tiltIndicator/reference/index.html): See `sector_profile*()`.
* [tiltIndicatorAfter](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/index.html) (see `prepare_pstr_*()` and `prepare_istr_*()`).

Note I'm working on the integration of tiltIndicator and tiltIndicatorAfter, so eventually there should be just one user-facing package, and only one set of `sector_profile*()` functions.

**Comment by maurolepore** [comment]
@bobresink, my answer might be a bit too general. Is there anything specifically you would like to know?

**Comment by maurolepore** [comment]
To cleanup my board I'll consider this done. We can always reopen is you need something else.
