### ISSUE TITLE
Going through output tables to identify data quality rules

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#544]
Hi @SKruthoff and @ysherstyuk . You can find the output tables [here](https://docs.google.com/spreadsheets/d/1pm3y2eYHVhDDevwebyld_zcfk0MUEdHMojcXx3-cU8s/edit#gid=46353651). Let's go through the output tables toeghther and identify data quality rules based upon them.

**Comment by AnneSchoenauer** [comment]
We went through emission profile product and company. @SKruthoff and @ysherstyuk do you need such a session also for the other output table? Was this helpful or not?

**Comment by bobresink** [comment]
@AnneSchoenauer is this task done from your point of view?

**Comment by AnneSchoenauer** [comment]
Yes :)
