### ISSUE TITLE
At product level, `sector_profile*()` should output `profile_ranking`

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#549]
Relates to https://github.com/2DegreesInvesting/tiltIndicator/issues/566
Relates to https://github.com/2DegreesInvesting/tiltIndicator/issues/581

--

To add more transparency it would be great to understand also what the sector emission reduction target (SERT). So I envisioning to include this datapoint also in the output table. Could you please check where this data point lies and how to include it in the output table?

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore and @kalashsinghal - please note that I don't know if this issue is a tiltIndicator or a tiltIndicatorAfter package. 

However, to update this ticket please find the following description. 

Description:
We need to enhance the visibility of our emission reduction efforts by including the Sector Emission Reduction Target (SERT) in our reporting. The SERT data point is labeled as "reductions" within the "sector_profile_any_scenarios.csv.gz" file. The goal of this task is to update our existing R script(s) to read this data and include it in the final output table that is presented to stakeholders. Please note - it is fine if the SERT data point is called  `reductions` - no need to rename it. 

I think it works similiar to the column isic_digit and isic_categorisation so it shouldn't be a big problem I guess which you @mauro wrote this [code](https://2degreesinvesting.github.io/tiltIndicator/articles/tiltIndicator.html#enriching-the-output) for right?

**Comment by kalashsinghal** [comment]
@AnneSchoenauer `reductions` column is ousted in tiltIndicator code and not tiltIndicatorAfter code. However, this column can be added in tiltIndicatorAfter code after calculating the risk categories through tiltIndicator. Please also confirm whether you need this column in product level table of Sector profile and Sector profile Upstream. right?

**Comment by AnneSchoenauer** [comment]
@kalashsinghal okay great! Yes please for the product level table of sector profile and sector profile upstream. 

@maurolepore please let me know if something is unclear and you need help.

**Comment by maurolepore** [comment]
This issue relates to https://github.com/2DegreesInvesting/tiltIndicator/issues/581, i.e. `add `profile_ranking` to the output.

--

`scenarios$reducitons` is identical to `profile_ranking`.

``` r
tiltIndicator:::aka("co2reduce")
#> [1] "reductions"
```

https://github.com/2DegreesInvesting/tiltIndicator/blob/7be30e95573b1998d9486d8aceecba6be309153c/R/spa.R#L42
