### ISSUE TITLE
Inconsistency on how the `tilt_sectors` are written

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#553]
If you look [here](https://docs.google.com/spreadsheets/d/1pm3y2eYHVhDDevwebyld_zcfk0MUEdHMojcXx3-cU8s/edit#gid=46353651), you can see that the column `tilt_sector`and `tilt_sector_input` is written differently. On the one hand `Land Use` is written in bigger capitalisations and in others `land use` is in small capitalisation. Can you please check where this inconsistency is coming from? Did you use different sector mappers?

**Comment by kalashsinghal** [comment]
@AnneSchoenauer Alphabets in one table is lower cased. I will resolve it. 

How you want the sectors to be formatted: `Camel Case` or `lower case`?

**Comment by bobresink** [comment]
Hi @kalashsinghal ,

Lets include this discussion in the meeting we have next week with Yana on the naming conventions. We propose to use lower_case formatting for column names throughout the process where possible. I will resolve this issue for now.

**Comment by AnneSchoenauer** [comment]
all lower case please

**Comment by AnneSchoenauer** [comment]
@bobresink and @ysherstyuk did you come to a conclusion here? Would be great to have this implemented for the 24th. :) Thanks both of you!

**Comment by bobresink** [comment]
Hi Anne, 

we discussed that for the sake of time, we are not going to a complete change to all the name as this could include more bugs in the process, but anything that is written inconsistently and needs resolving for now should be written lower case. As part of the to-be data model the restructuring will include new naming conventions. Closing this issue.
