### ISSUE TITLE
Question: do we also have the column `multiple_matches` as `TRUE

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#555]
Dear @bobresink , I was looking at the output tables again and I had the questions if in the end we also included multiple matches in our data set. The dataset that I saw only has `FALSE` values for the column `multiple_matches`. Would be great to hear what you think about this!

**Comment by bobresink** [comment]
Hi anne, yes we also included multiple_matches in our dataset. However, the number of products with multiple matches was quite low. I would have to look into why the column only has FALSE values, but I'm sure we included multiple matches.
