### ISSUE TITLE
Reviewing Anne's review

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#558]
Dear @maurolepore,

First of all - well done with the tiltIndicator Package - it all runs super smoothly! :) 

Could you please go through this ticket [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/522) and tell me what you think? It would be great if you could answer those three questions: 

- Help page: I think for you the most interesting is what I have done with the Help pages. However, I think I do need your help here. I think what would be really valuable is also reviewing for example how the threshold is done - so to make sure that the key methodological decisions are implemented in the code. Could you help me how to figure out to open functions within functions? I didt it with `print(tiltIndicator:::emissions_profile_any_at_product_level` but then there are again new functions. 
- Toy data set: I sometimes don't understand the toy data set but most likely this is also something for data management. Shall I involve Kalash here? Where did you get the data from?
- Get started: I think here it is more about the documentation - maybe we can also discuss that I might be able to change some words here. If not also happy to pre-write it and you fill it in? What do you think?

After those high-level questions are clear, and your first review of my review, I think we can create tickets based on overview sheet ticket that I closed now. Thanks!

**Comment by maurolepore** [comment]
Thanks Anne for taking the time to review tiltIndicator. Your input is super important. I know it's very time consuming now but I'm sure it'll become a lot faster and smoother with practice. 

Your questions seem to be of two types: Conceptual and workflow. 

Conceptual questions like "why dataset `x` has column `y`" are harder for me to answer. To trace back the answer the path is me, Bob/Kalash, Tilman, and you. We can tackle each question case by case and as we gather new knowledge it would be great to capture it by updating the data, code, and documentation.

Workflow questions like "how to I edit the text I see in the website" are easy to answer. And once you learn it for tiltIndicator you can do it with any package (in tilt and beyond). However I think they are better answered interactively. I suggest we meet I can show you how you can do the workflow things you want to do. Maybe we use some of our meeting-time today.

**Comment by AnneSchoenauer** [comment]
Okay perfect! Thanks Mauro that helped! I will follow up with concrete and actionable tickets and prioritise them according on how crucial they are! :)

**Comment by maurolepore** [comment]
@AnneSchoenauer in our meeting we covered how to do a few things directly on GitHub. But I realize I showed you how to find code and code-related tests, but I forgot to show you how you can edit text. Also I could show you how to do those same things on RStudio then push them to GitHub -- instead of directly on GitHub.
