### ISSUE TITLE
Compute `profile_ranking` using the entire `ecoinvent` dataset

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#566]
UPDATE: Note `values_to_categorize` was renamed to `profile_ranking`.

- [x] https://github.com/2DegreesInvesting/tiltIndicator/issues/598
- [x] #609 
- [x] https://github.com/2DegreesInvesting/tiltIndicator/issues/596
- [x] https://github.com/2DegreesInvesting/tiltIndicator/issues/603
- [x] https://github.com/2DegreesInvesting/tiltIndicatorBefore/issues/6
- [x] https://github.com/2DegreesInvesting/tiltIndicatorBefore/issues/7
- [ ] https://github.com/2DegreesInvesting/tiltToyData/issues/7
- [x] https://github.com/2DegreesInvesting/tiltIndicator/issues/606

----

**Description:**

Issue: I've observed that our current benchmark calculations for product carbon footprints might not align with our intended methodology. The reason is that the product "market for coffee, green beans" is regardless of their benchmark in their PCTR category always a high product. This is not logical as coffee would be compared to cars and steel, which naturally would have a higher cabon footprint than coffee. I attached the PCTR output here for EuroCaps

Expected Behavior: When comparing a product's carbon footprint, it should be benchmarked against all products from the ecoinvent LCA database.

Current Behavior: It seems the system is benchmarking the product's carbon footprint against only those products produced by a sample set of companies we assess, rather than the entirety of the ecoinvent database.

**Steps to Reproduce:**

- [ ] Select "market for coffe, grean beans" product's carbon footprint for benchmarking.
- [ ] Observe the list of products it is being compared against.
- [ ] Confirm if this list is sourced from our sample set of companies (only EuroCaps and their suppliers) or the complete ecoinvent database.
- [ ] Requested Action: Please review the code and logic responsible for selecting products for benchmark comparisons. If the current behavior is confirmed, adjust the methodology to ensure benchmarks are drawn from the full ecoinvent LCA database and not just our sample set of companies.

Notes: If time allows, after identifying the issue, please proceed with the necessary fixes. If the fix is time-intensive, kindly report back with your findings and an estimated timeline for the correction.

**Attachement:** 
[pctr_product_result_EuroCaps.csv](https://github.com/2DegreesInvesting/tiltIndicator/files/13021306/pctr_product_result_EuroCaps.csv)

**Comment by maurolepore** [comment]
Thank @AnneSchoenauer 

In your comment I see that you attached a .csv file with a result. Can you share the data and code you used? 

I need to create a reproducible example that captures the problem you see. That way I will be able to understand what you mean, and able to track the exact lines of code that result in the unexpected behaviour.

**Comment by AnneSchoenauer** [comment]
Dear  @maurolepore, thanks for your answer. 

I received the output tabel from @bobresink  and @kalashsinghal. @bobresink  or @kalashsinghal  could you please provide @maurolepore with the following code so that he can reproduce the issue? 

@bobresink do we have a list of all ecoinvent activities and the geographies that we use? This would be the list that we would need to do the benchmarks with. So that our ep_product that we matched should be compared with all products from ecoinvent. Could you please provide this if it doesn't exist? @kalashsinghal this might require some changes in the tiltIndicator package. 

If you all have questions about the problem - let me know and we have a meeting! Thanks!

**Comment by kalashsinghal** [comment]
@maurolepore [Here](https://drive.google.com/drive/folders/1AcdqNNo-_b738ZZ54Nw-Vgic42U-OWiP) you can find all input data for Eurocaps.

I am only attaching the code to produce PCTR product result at the moment. Please let me know if you need code for other indicator results as well!

[pctr_product_eurocaps.R.zip](https://github.com/2DegreesInvesting/tiltIndicator/files/13267896/pctr_product_eurocaps.R.zip) (Only the path of files needs to be updated in the code)

**Comment by maurolepore** [comment]
Thanks @kalashsinghal, is this public?

**Comment by AnneSchoenauer** [comment]
@maurolepore to jump in - the data is not public, no. Thanks!

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore thanks for investigating and the [YouTube ](https://youtu.be/hErN0A-u040 ) video really helped! this debug_once() function is amazing! 

Anyway, coming now to the issue - i spoke to Tilman to be 100% sure and unfortunately I was right. The methodology says (and this is also what we discussed with the banks) that by benchmarking the products are compared to all data of ecoinvent. Therefore, I guess you will now need a list of all ecoinvent data. 

I would follow up with Kalash on this as he has this data available. I don't want to be prescriptive but am I right that what you would need is a list of the following variables: 

```
- activitiy_uuid_product_uuid,
- co2_footrpint, 
- tilt_sec
- tilt_subsector
- unit
- isic_sec
- ei_activity_name
```

Would that be also a good time of doing a reprex? So that you know what to do? Even though I won't have time tomorrow for this... but just checking in if the issues is somehow clear or if it needs more explanations from my side, e.g. with a reprex? Let me know how best to proceed further - I can otherwise also create little toy data? Just let me know what would be the best for you please. 

Thanks!
Best
Anne

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer for confirming. 

(For the record, the issue #581 has important details about this problem, and the video that Anne mentions here.)

The change we need seems pretty deep and I'm not sure yet how to tackle it. 

I could try develop a reprex to expose the current bad behaviour. But since this is at the core of the methodology, you may the be best one to try draft how we may be able to do what you want.

If you already have an idea, yeah, go ahead and explain it with toy data -- maybe a lil spreadsheet. Then we can go from there.

My intuition suggests we might pre-compute the ranks for all products and then simply assign the rank to each product of a company by matching it with the same product in the dataset with the pre-computed ranks. But I may be totally wrong :-)

**Comment by AnneSchoenauer** [comment]
Hi Mauro! Yes that would be how I would solve it and I was thinking about it yesterday! In my head I build the toy data but I have some meetings in the morning so I am only able to work on this in the afternoon unfortunately! Best Anne

**Comment by maurolepore** [comment]
Okay, if you think my idea might work, then I may be able to write a lil draft myself before you're available.

**Comment by AnneSchoenauer** [comment]
Hi @maurolepore one of my meetings was cancelled so I tried to put it into code what I was thinking what we could do but as I said I am also not 100% sure if this is the right thing but maybe it helps. 

Let's assume the ecoinvent dataset looks like this: 

`
library(dplyr)
library(tibble)

# Create the data
data <- tibble(
  co2_footprint = c(176.0, 58.1, 4.95, 12.5, 2.07),
  tilt_sec = c("Industry", "Industry", "Steel", "Agriculture", "Industry"),
  unit = c("unit", "unit", "kg", "kg", "kg"),
  isic = c(2560, 2560, 2870, 1780, 2679),
  ei_activity_name = c("cookstove production", "microwave oven", "market for steel", "cheese production", "market for sealing"),
  low_threshold = c(0.333, 0.333, 0.333, 0.333, 0.333),
  high_threshold = c(0.667, 0.667, 0.667, 0.667, 0.667)
)`

Let's now calculate for the whole ecoinvent dataset (which is then our population) different benchmarks. I did this now as I understood you are doing it right now with the following code: 

``
# Add the variable_to_categorise_tilt_sec column
data <- data %>%
  group_by(tilt_sec) %>%
  mutate(variable_to_categorise_tilt_sec = rank(co2_footprint) / n())

# Add the variable_to_categorise_tilt_sec_unit column
data <- data %>%
  group_by(tilt_sec, unit) %>%
  mutate(variable_to_categorise_tilt_sec_unit = rank(co2_footprint) / n())

# Add the variable_to_categorise_isic column
data <- data %>%
  group_by(isic) %>%
  mutate(variable_to_categorise_isic = rank(co2_footprint) / n())

# Add the variable_to_categorise_isic_unit column
data <- data %>%
  group_by(isic, unit) %>%
  mutate(variable_to_categorise_isic_unit = rank(co2_footprint) / n())

# Add the variable_to_categorise_all column
data <- data %>%
  ungroup() %>%
  mutate(variable_to_categorise_all = rank(co2_footprint) / n())

# Add the variable_to_categorise_all_unit column
data <- data %>%
  group_by(unit) %>%
  mutate(variable_to_categorise_all_unit = rank(co2_footprint) / n()) %>%
  ungroup()  # make sure to remove grouping after all operations

# View the data
print(data)
``

Now let's assume that we only have some matched products between europages and ecoinvent. So that means not all of the activities in ecoinvent would be suitable for our analysis. You could then filter those activities that are important for us like this: 

``# Filter for a specific ei_activity_name
specific_name <- "cookstove production"
data_filtered <- data %>%
  filter(ei_activity_name == specific_name)

print(data_filtered)
``

Please note that I think to avoid mistakes we should not filter on ei_activity_name but on the activity_uuid_product_uuid but I used the data that you showed me in the YouTube video and I wasn't able to see the whole id. 

Is this clear? Or does that make sense? Happy to hear your comment.

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer for your examples <3

Here are some thoghts/questions. You may not have the answer, and you likely think I should know, ahah.

It makes sense but it seems to be exactly what the code is doing, so the only difference I see is that the `products` dataset that we are currently using is incomplete. If we replace it with a dataset with the full ecoinvent products the result should be what you want?

So if our `products` dataset is not the dataset that has all ecoinvent products, then what is the `products` dataset that we are using? (Yeah, it's unclear. It would be great to have each dataset well documented. I'm quite able to document the functions based on what I see they do, but I don't know enough about where the data comes from, so I can't write useful documentation.)

And if the `products` dataset is not user-supplied, then why are we computing the ranks on the fly? 

### BTW: How to turn your code into a reprex

* Select the code
* Go to Addin > reprex selection

![image](https://github.com/2DegreesInvesting/tiltIndicator/assets/5856545/b8dcfe7d-e7a0-406e-8c17-7ba8a427eaa8)

**Comment by AnneSchoenauer** [comment]
Hi @maurolepore - I can answer your question and that is what I meant with this comment [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/566#issuecomment-1799257552). What I mean here is that we need a dataset coming from ecoinvent. And this dataset would include all products that we have in ecionvent. The dataset that you use in the tiltIndicator package is the dataset where we only have ep_products that were matchable to ecoinvent_activities included. So only those ones that after webscraping the data from europages were able to be matched to the ecoinvent dataset.  Therefore, in my understanding the whole workflow as I see it would be: 

- [ ]  Have a list of all ecoinvent activities 
- [ ] Calculate all benchmarks
- [ ] Have a list of the matchable europage products with ecoinvent activities (this one is the data that you have right now)
- [ ] Pick the matched ecoinvent activities from the list of all ecoinvent activities and merge the benchmarks to them

I am now asking if you could help me how the list from all ecoinvent products would need to look like so that Kalash can prepare this list. In my understanding it would be the following list right? 

```
- activitiy_uuid_product_uuid,
- co2_footprint, 
- tilt_sec
- tilt_subsector
- unit
- isic_sec
- ei_activity_name
```

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer, much clearer now.

Overall it's great news because it means we can move the ranking computation outside of the main tiltIndicator functions. This should simplify the code and make execution faster. 

The code may stay in the tiltIndicator package but would be used internally -- whenever we can to update the internal ecoinvent data on which we calculate the rankings.

RE which columns to include in the ecoinvent dataset, I mostly agree:

* I think we only really need the `*uuid` of each product, its `co2_footprint`, and its value for each benchmark. I see the benchamrks we use are these, but some of them are composed from others: "all", "isic_sec", "tilt_sec", "unit", "unit_isic_sec", "unit_tilt_sec".
* I believe `ei_activity_name` does not participate in the calculations but would be good to have for more readable context (as the `*uuid` us useful but not meaningful).
* Also `tilt_subsector` doesn't seem to participate, but if you think it adds useful context, then go ahead.

I think I can start drafting some code with a toy ecoinvent dataset.

**Comment by AnneSchoenauer** [comment]
I followed up with this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/592). I put it as high priority but for sprint 4 for Kalash - so that Kalash can finish with other tasks first. I did this @maurolepore as I understood you can keep you busy with the toy data first. Please let me know if you need the real data before next week so I can prioritise with Kalash.

**Comment by maurolepore** [comment]
Sounds good. 

What I'm thinking is this:

In tiltindicatorBefore:

1. Rank products across the entire `ecoinvent` dataset, using the code we currently use in tiltIndicator.
2. Match the `co2` dataset (either products or inputs) to the `ecoinvent` dataset so that the `co2` dataset gains the ecoinvent-rankings (which in tiltIndicator we call `values_to_categorize`).

In tiltIndicator:

3. Match the `companies` dataset to the (now enhanced) `co2`. This way each company gains the ecoinvent-rankings. 

Note that we no longer compute the rankings in the tiltIndicator.

@AnneSchoenauer:

* What do you think about this process?
* Where should we compute the risk categories from the rankings -- does is make sense to do it in tiltIndicatorBefore so that the `co2` dataset (i.e. products/inputs) already gains those risk-categories?

**Comment by AnneSchoenauer** [comment]
@maurolepore, 

Thanks a lot for this. I need to say I like the idea that the benchmarks and risk categories are always calculated in the tiltIndicatorBefore package. However, I don't quite understand the order of things. You write that we 1. rank and then 2. add the Co2 data. Ecoinvent is our Co2 database. So ecoinvent gives up activities and their Co2_footrpint. We then need to rank the Co2 footprint. So I think we need just the ecoinvent list with all Co2 footprints and then rank them with the code that you provide in the tiltIndicator package and then we match the company dataset with it in the tiltIndicator pacakge. Your steps would then be: 

1. Full list of ecoinvent (with Co2 data)
2. Rank with tiltIndicator Code
---
3. Match the companies 

To the sector profiles. I think we could do exactly the same. I think the benchmarks for the sector profiles can also be pre-calculated actually in the tiltIndicatorBefore. But to understand this better, could you debug_once() also the benchmarks for the sector profiles? So similiar to the code snippet that you gave me [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/581#issuecomment-1794946555). No need to do a video but if you have time it would be great if you could debug_once() so that I can see how the benchmarks for the sector profiles were calculated. I could also implement it thanks to your video as well but it would cost me some time and I am a bit under water right now Mauro. I will then follow up if we can align the two approaches (emission profiles and sector profiles) thereafter. Thanks for supporting!

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer for your careful attention.

Sorry for confusing you with the 'co2' dataset. I use the word 'co2' to collectively refer to the datasets containing products and inputs (aka upstream products). In the help file of [emissions_profile()](https://2degreesinvesting.github.io/tiltIndicator/reference/emissions_profile.html) you'll see this:

emissions_profile(companies, co2, low_threshold = 1/3, high_threshold = 2/3)

To make things simpler let's call it 'products'. So we currently use 'companies' and 'products'. You explained that 'products' is a smaller version of 'ecoinvent' -- containing only products that exist in europages. I tried to reflect this in my reprex. 

So my idea is to (1.) compute the rankings with the full 'ecoinvent' dataset (which may contain private data?), then (2.) reduce it to only the products that exist in europages. The result would be just like the products dataset we use now but with a new column containing the ranking of each product in the full ecoinvent dataset. Finally we (3.) match the (enhanced) products dataset with the companies dataset.


Or do you now think that we can get rid of the products dataset?

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore - thanks for explaining! This makes a lot of sense! Can you coordinate with @kalashsinghal here to do the 1) and 2) step? And you take care of 3). I guess your reprex in a new ticket should be sufficient for @kalashsinghal right. I also followed up with this ticket [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/592) so that Kalash knows which full ecoinvent list (private data) we need

**Comment by maurolepore** [comment]
Good, we have a plan for the `emissions_profile*()` functions :-).
I'll follow up with a new issues with tasks for me and for Kalash.

For the `sector_profile*()` functions, I owe you an exploration of what the situation currently is. I'll follow up here then to discuss if the same plan applies for these functions or if we need something a bit different.

**Comment by maurolepore** [comment]
@AnneSchoenauer, I [slacked you a video](https://2investinginitiative.slack.com/archives/D01JA76GDTR/p1699606499168299) exploring `sector_profile*()` . 

In short, it already does what we want to do with `emissions_profile*()` -- i.e. the `values_to_categorize` are added in "tiltIndicatorBefore" as the column `reductions` of the dataset scenarios. 

Note the categorization as "low", "medium", or "high" is done in tiltIndicator and in exactly the same way for both `sector_profile*()` and `emissions_profile*()`. Can you confirm that's conceptually correct?

**Comment by AnneSchoenauer** [comment]
> @AnneSchoenauer, I [slacked you a video](https://2investinginitiative.slack.com/archives/D01JA76GDTR/p1699606499168299) exploring `sector_profile*()` .
> 
> In short, it already does what we want to do with `emissions_profile*()` -- i.e. the `values_to_categorize` are added in "tiltIndicatorBefore" as the column `reductions` of the dataset `scenarios`.
> 
> Note the categorization as "low", "medium", or "high" is done in tiltIndicator and in exactly the same way for both `sector_profile*()` and `emissions_profile*()`. Can you confirm that's conceptually correct?

Dear @maurolepore! Thanks for the video and good news are that it seems to be then pretty similiar process as we now will implement it for the emission_profile() which is nice! Could you please do me a favour and this is the last review that I would need to do with the tiltIndicator package. Could you please let me know how the thresholds are implemented? So I would like to understand further how the values_to_categorise (aka reductions) are then categorised in the risk profiles and for this I would like to understand better how the code implements the thresholds. Thanks!

**Comment by maurolepore** [comment]
Sure, here you go:

https://2investinginitiative.slack.com/archives/D01JA76GDTR/p1699871478019569
