### ISSUE TITLE
ISIC digits of length less than four are valid and should be allowed to pass through the `tiltIndicator` package

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#568]
@maurolepore I found out that its not necessary that the ISIC 4-digit column should always have length of 4. Please have a look at the column `isic_4digit` in this file: https://github.com/2DegreesInvesting/NLPTiltMatch/blob/main/indicator_preparation/input/tilt_isic_mapper_2023-07-20.csv. There could be ISIC values as `06` and `201`. Therefore, I request you to allow such values to pass through the code which is currently being stopped by the error given by this function `check_string_lengh`: 
```Error in `check_string_lengh()` at tiltIndicator/R/emissions_profile_any_at_product_level.R:32:2:
! All values of `pull_isic(x$co2)` must have length 4.```

cc` @AnneSchoenauer Please correct me if I am wrong!

**Comment by AnneSchoenauer** [comment]
Dear @kalashsinghal, so it is true that we would want those ep_products also included as a matching. However, what would be crucial is that for the benchmarking isic / isic_unit only the 4 digits are compared to each other as they are on one level. So to calculate the benchmark isic, and isic_unit it is correct do delete isic 2 and 3 digit products. If it is for the benchmark tilt sectors please keep them in and also for the benchmark all as well. Happy to explain further if needed!

**Comment by maurolepore** [comment]
@kalashsinghal and @AnneSchoenauer, 

Do you mean that  `"06"` and `"0006"`  mean different things?

If not then `"06"` is a raw version of `"0006"` and you can convert one to the other like this:

``` r
library(stringr)

# Input to tiltIndicatorBefore
isic_raw <- c("1234", "12")
isic_raw
#> [1] "1234" "12"

# Output of tiltIndicatorBefore and input to tiltIndicator
isic_4digit <- stringr::str_pad(isic_raw, width = 4, pad = "0")
isic_4digit
#> [1] "1234" "0012"
```

<sup>Created on 2023-10-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by maurolepore** [comment]
In any case it would be nice to see a reprex of the problem you see. I think titIndicator does some padding so I'm unsure how you got there.

**Comment by kalashsinghal** [comment]
Followup with #571
