### ISSUE TITLE
Include `clustered` info in the outputs of Indicators' product level results

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#573]
relates to #572 

@maurolepore As you can see from the below reprex, the `company_id` "a" has a `clustered` product "a" in `companies` dataset. However, there is null value in the `clustered` column of `sector_profile_product` dataset. Please make the required changes in the code so that the `clustered` column of `sector_profile_product` carry info from the `clustered` column of `companies` dataset. 

Also, please include the `clustered` info at product level for the other three indicators as well. Thanks! 
cc' @AnneSchoenauer 

``` r
devtools::load_all()
#> ℹ Loading tiltIndicator
library(dplyr, warn.conflicts = FALSE)

companies <- example_companies()[1L, ]
companies[1, "sector"] <- NA_character_
companies[1, "activity_uuid_product_uuid"] <- NA_character_
companies[1, "subsector"] <- NA_character_
companies[1, "tilt_sector"] <- NA_character_
companies[1, "tilt_subsector"] <- NA_character_
companies[1, "type"] <- NA_character_
companies 
#> # A tibble: 1 × 8
#>   company_id clustered activity_uuid_product_uuid sector subsector tilt_sector
#>   <chr>      <chr>     <chr>                      <chr>  <chr>     <chr>      
#> 1 a          a         <NA>                       <NA>   <NA>      <NA>       
#> # ℹ 2 more variables: tilt_subsector <chr>, type <chr>

scenarios <- read_csv(toy_sector_profile_any_scenarios())

sector_profile_product <- sector_profile(companies, scenarios) |> unnest_product()
sector_profile_product
#> # A tibble: 1 × 10
#>   companies_id grouped_by risk_category clustered activity_uuid_product_uuid
#>   <chr>        <chr>      <chr>         <chr>     <chr>                     
#> 1 a            <NA>       <NA>          <NA>      <NA>                      
#> # ℹ 5 more variables: tilt_sector <chr>, scenario <chr>, year <dbl>,
#> #   type <chr>, tilt_subsector <chr>
```

<sup>Created on 2023-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

P.S. I tried to add the `clustered` info using tiltIndicatorAfter code, however it gave weird multi-match issue after the match. Hence, I thought it would be great if this issue could be resolved in tiltIndicator code. Please let me know if you think otherwise!

**Comment by maurolepore** [comment]
Thanks @kalashsinghal, but unfortunately I don't think there is a solution to that.

For the value of `clustered` to appear in the output the `companies` dataset must match the `scenarios` dataset, and that only happens when all three columns match: `sector`, `subsector` and `type`.

Your reprex uses a `companies` dataset with `NA` in `sector`, `subsector` and `type`, so there is no way that it would match `scenarios`. 

Here is a simpler version of your reprex, first showing that the value of `clustered` does appear in the output when `companies` matches `scenarios`, and then showing than `NA` in any of `sector`, `subsector` or `type` causes a missmatch so the output is an "empty result".

``` r
library(tiltIndicator)

# `companies` and `scenarios` match by `sector`, `subsector`, and `type`
companies <- tibble::tribble(
  ~company_id, ~clustered, ~activity_uuid_product_uuid, ~sector, ~subsector, ~tilt_sector, ~tilt_subsector, ~type,
          "a",        "a",                         "a", "total",   "energy",          "a",             "a", "ipr"
)
scenarios <- tibble::tribble(
   ~scenario, ~region, ~sector, ~subsector, ~year,  ~value, ~reductions, ~type,
  "1.5c rps", "world", "total",   "energy",  2030, 25711.9,        0.26, "ipr"
)

sector_profile(companies, scenarios) |> unnest_product()
#> # A tibble: 1 × 10
#>   companies_id grouped_by        risk_category clustered activity_uuid_product…¹
#>   <chr>        <chr>             <chr>         <chr>     <chr>                  
#> 1 a            ipr_1.5c rps_2030 high          a         a                      
#> # ℹ abbreviated name: ¹​activity_uuid_product_uuid
#> # ℹ 5 more variables: tilt_sector <chr>, scenario <chr>, year <dbl>,
#> #   type <chr>, tilt_subsector <chr>

# Bad
companies <- tibble::tribble(
  ~company_id, ~clustered, ~activity_uuid_product_uuid, ~sector, ~subsector, ~tilt_sector, ~tilt_subsector, ~type,
          "a",        "a",                         "a",      NA,   "energy",          "a",             "a", "ipr"
)
scenarios <- tibble::tribble(
   ~scenario, ~region, ~sector, ~subsector, ~year,  ~value, ~reductions, ~type,
  "1.5c rps", "world", "total",   "energy",  2030, 25711.9,        0.26, "ipr"
)
sector_profile(companies, scenarios) |> unnest_product()
#> # A tibble: 1 × 10
#>   companies_id grouped_by risk_category clustered activity_uuid_product_uuid
#>   <chr>        <chr>      <chr>         <chr>     <chr>                     
#> 1 a            <NA>       <NA>          <NA>      <NA>                      
#> # ℹ 5 more variables: tilt_sector <chr>, scenario <chr>, year <dbl>,
#> #   type <chr>, tilt_subsector <chr>

# Bad
companies <- tibble::tribble(
  ~company_id, ~clustered, ~activity_uuid_product_uuid, ~sector, ~subsector, ~tilt_sector, ~tilt_subsector, ~type,
          "a",        "a",                         "a", "total",         NA,          "a",             "a", "ipr"
)
scenarios <- tibble::tribble(
   ~scenario, ~region, ~sector, ~subsector, ~year,  ~value, ~reductions, ~type,
  "1.5c rps", "world", "total",   "energy",  2030, 25711.9,        0.26, "ipr"
)
sector_profile(companies, scenarios) |> unnest_product()
#> # A tibble: 1 × 10
#>   companies_id grouped_by risk_category clustered activity_uuid_product_uuid
#>   <chr>        <chr>      <chr>         <chr>     <chr>                     
#> 1 a            <NA>       <NA>          <NA>      <NA>                      
#> # ℹ 5 more variables: tilt_sector <chr>, scenario <chr>, year <dbl>,
#> #   type <chr>, tilt_subsector <chr>

# Bad
companies <- tibble::tribble(
  ~company_id, ~clustered, ~activity_uuid_product_uuid, ~sector, ~subsector, ~tilt_sector, ~tilt_subsector, ~type,
          "a",        "a",                         "a", "total",   "energy",          "a",             "a",    NA
)
scenarios <- tibble::tribble(
   ~scenario, ~region, ~sector, ~subsector, ~year,  ~value, ~reductions, ~type,
  "1.5c rps", "world", "total",   "energy",  2030, 25711.9,        0.26, "ipr"
)
sector_profile(companies, scenarios) |> unnest_product()
#> # A tibble: 1 × 10
#>   companies_id grouped_by risk_category clustered activity_uuid_product_uuid
#>   <chr>        <chr>      <chr>         <chr>     <chr>                     
#> 1 a            <NA>       <NA>          <NA>      <NA>                      
#> # ℹ 5 more variables: tilt_sector <chr>, scenario <chr>, year <dbl>,
#> #   type <chr>, tilt_subsector <chr>
```

The "weird" multi-match that you see might be from trying to join the output for a given company to all the values of `clustered` associated to that company in the input `companies` dataset.

**Comment by AnneSchoenauer** [comment]
Hi both of you - thanks for taking care of this. 

**Issue every company needs a sector/subsector**
I am not quite sure if I understand the issue... can you maybe explain to me why the companies can only be matched to clustered when we have sector and subsector for the company? The problem that I see is that the sector and subsector are on the product level. So each clustered should have a sector and subsector and then this clustered should be related to one company. A company can have many products and therefore also products coming from different sector and subsectors. So the sector/subsector is on product (clustered) level. 

**Every company should have a ep_product**
When we webscraped the data we had per company many ep_products. Those ep_products were pre-processed. Actually all of them should have a tiltsector and tilt subsector (for the sector profiles) and some of them were able to be matched with ecoinvent (for the emission profiles). There might be some excemption. @kalashsinghal can you clarify if the input data for the tiltIndicator package have for each company at least one product (regardless if it is matched to ecoinvent or not) and if all products have a sector/subsector? If this is the case then we know that the products might be kicked out through the tiltIndicator(Before) package, if not we know that we have the wrong input data. 

Let me know if you have questions and thanks!

**Comment by kalashsinghal** [comment]
@maurolepore I think problem why `clustered` value doesn't appear in the final output is because of this line in the code: https://github.com/2DegreesInvesting/tiltIndicator/blob/2192074cb2264e905510f351c0c4092f07def7ae/R/utils.R#L136

This line convert `clustered` values to null values if `risk_category` is null too. Please recheck your findings as I found this after debugging the code. I could not create a reprex due to some issue with importing. Please let me know if you need a reprex to understand further! Thanks!

**Comment by kalashsinghal** [comment]
@AnneSchoenauer For this comment:
> Every company should have a ep_product

I checked and found that every company has atleast a single `clustered` product, however not every `clustered` is assigned a `tilt_sector ` and `tilt_subsector`. This means there are also cases where a single company has `clustered` but not a single `tilt_sector ` and `tilt_subsector` for those clustered products. Is it clear?

**Comment by AnneSchoenauer** [comment]
Dear @kalashsinghal, 

Thanks a lot for this! WIth regard to this 

> I checked and found that every company has atleast a single clustered product, however not every clustered is assigned a tilt_sector  and tilt_subsector. This means there are also cases where a single company has clustered but not a single tilt_sector  and tilt_subsector for those clustered products. Is it clear?

Could you please make a list for all clustered that have not a single tilt_sector and tilt_subsector please? I will then investigate why this is the case because it actually shouldn't be like this. 


> However, I checked and found that not every company is assigned a sector and sub_sector (these are ipr_sectors and ipr_subsectors). Do you still have questions?

And to the other comment could you also create a list with all the companies and their products that were not assigned to any tilt_sector and tilt_subsector? I also always assumed that each company in our dataset that have a product will also have a tilt_sector or tilt_subsector. So I would also need to investigate this further if it is right that for some companies we don't have a tilt_sector and tilt_subsector.

**Comment by maurolepore** [comment]
Closing in favor of tiltIndicator #587 so we don't have duplicated issues.
