### ISSUE TITLE
No distinct isic categorisations for ep_product

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#589]
Following up with this issue here: https://github.com/2DegreesInvesting/NLPTiltMatch/issues/34 and here: https://github.com/2DegreesInvesting/NLPTiltMatch/issues/81. 

Anne needs to decide on how to handle this and will follow up with how to implement this cc'ing @kalashsinghal and @bobresink

**Comment by kalashsinghal** [comment]
Reminder for myself: Write a test after the fix

**Comment by AnneSchoenauer** [comment]
Dear @kalashsinghal and @bobresink, 

I try to explain what happened and what I found out when looking at this csv file [here](https://docs.google.com/spreadsheets/d/1H5yHEfvcVpLRjb-q32gq-8Qu_ab4G4WZgB2Cdze3sEY/edit#gid=1762477266). This is a summary of my findings. I will follow up more concretely with other tickets. 

Please note that there are two cases why we have some duplicated isic per ep_products. 

Case 1: ep_product is produced from different companies that have a different main_activity. In this case the same ep_product can be for example traded or manufactured. Depending on what the company does with the ep_product the ep_product can stem from different isic. This is correct. For this the following is derived: 

- [ ] It is not the case that every ep_product needs to have a distinct isic categorisation and therefore a distinct tilt_sector or tilt_subsector. However it is more the case that each type of company combined with ep_product will have a different isic categorisation and therefore tilt_sector or tilt_subsector. Therefore, we need when we match back the ep_products to the companies, we need to macth not only the ep_products but also the main_activity of the company. Please note that this is note that even though the companies have many main_activities in europages that we only differentiate between the main_activities that are producing/manufacturing and those main_activities that are the market. I will follw up with a little reprex now so that you will understand what I mean with this exactly. cc'ing @kalashsinghal (I will follow up with a reprex today)
- [ ] When we do the sector resolving, we actually also would need to not only let GPT decide on the products but also with the main activity involved. 'ccing @bobresink. I will also follw up with a different ticket on this and we can prioritise next week. 


Case 2: there are multiple matches possible as the main_activitiy is missing from companies. In those cases what we do we calculate the Co2_averages. In those cases, I think it is fine if we have multiple sectors for one ep_product. The question is just how to best implement this. I will also follow up here with a different ticket but this has a fewer priority than the above.

**Comment by AnneSchoenauer** [comment]
@kalashsinghal please note that as a test we would then have that each activity_uuid_product_uuid have unique ISICs and tilt_secs and that every main_activity and ep_clustered have unique ISICs. And here the main_activities are separated in two groups (ordinary transforming activities and market activities) which can be seen [here](https://docs.google.com/spreadsheets/d/1BuM9jRJE-JsTKYokgjFz5rGYS-rl-ii3LlC3cYP2AiU/edit#gid=0).
