### ISSUE TITLE
Document the `co2` dataset based on Anne's explanation

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#591]
Explain that the `co2` dataset (a.k.a. products or inputs) that we use in tiltIndicator (e.g. in `emissions_profile(companies, products)`) contains products scraped from europages that match a product in the ecoinvent dataset. The ecoinvent dataset is larger and should be used as the canonical source of data to rank products based on their transition risk.

This refined understanding I got from here:

> The {`co2`} dataset that you use in the tiltIndicator package is the dataset where we only have ep_products that were matchable to ecoinvent_activities included. So only those ones that after webscraping the data from europages were able to be matched to the ecoinvent dataset.

_Originally posted by @AnneSchoenauer in https://github.com/2DegreesInvesting/tiltIndicator/issues/566#issuecomment-1802001165_

**Comment by kalashsinghal** [comment]
This issue is already resolved via `profile_rank` column in latest version
