### ISSUE TITLE
Providing full ecoinvent data list to Mauro to correct benchmarking issue in tiltIndicator package

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#592]
Relates to #566 

Dear @kalashsinghal , 

Regarding this ticket here, @maurolepore and I discussed that Mauro would need a data frame from ecoinvent with the following columns: 

- activitiy_uuid_product_uuid,
- ei_activity_name
- co2_footprint, 
- tilt_sec
- tilt_subsector
- unit
- isic_sec

Please note that this dataframe really needs to include ALL ecoinvent activities that are filtered by geography. So what you would need is first from @bobresink the geography filters. The step would then be to have the full list, filter it by all geographies that are in the geography filter and then map with the sector mapper the tilt_sec and tilt_subsector to the isic_sec and just select the above columns. 

Please let me know if there are any mistakes or if problems arrive!

Thanks a lot!
All the best
Anne

**Comment by maurolepore** [comment]
@AnneSchoenauer this issue wouldn't belong to tiltIndicator. @kalashsinghal do we already have a tiltIndicatorBefore package?

**Comment by maurolepore** [comment]
Closing in favor of https://github.com/2DegreesInvesting/tiltToyData/issues/7
