### ISSUE TITLE
Chose a better name for `values_to_categorize`

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#598]
Relates to 2DegreesInvesting/tiltIndicator#566

We now have the opportunity to agree on a good name for what tiltIndicator internally calls `values_to_categorize`.

* In `emissions_profile*()` these are the values that result from computing `rank(co2_footprint) / lengh(co2_footprint)`.
* In `sector_profile*()` these are the values in `scenarios$reductions`, and I don't know how they are calculated.

Some ideas with some help from ChatGTP:

1. `rank_over_lengh`

2. `rank_over_n`

3. `average_rank`

> If you're looking for a name for the expression "rank(x) / length(x)," you might consider calling it the "average rank" or "mean rank" of the elements in the set x. 

> When a magnitude is said to be "averaged," it generally means that the values contributing to that magnitude have been combined in a way that represents their central tendency. 

4. `normalized_rank`

> Normalizing a magnitude means scaling it to ensure that it falls within a specific range or has a certain property. The goal is often to make it comparable or easier to work with, especially when dealing with data that might have different scales or units.

5. `standardized_rank`

> Standardizing a magnitude typically refers to transforming it in a way that it conforms to a standard scale or distribution. 

6. `ecoinvent_ranking`

Would this be accurate for both `emissions_profile*()` and `sector_profile*()`?

8. `risk_ranking`

9. ...?

Note the name should work for both `emissions_profile*()` and `sector_profile*()` functions.

@AnneSchoenauer what do you think?

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore, 
Thanks a lot for this!
I would like to decide for `profile_ranking`. 
Thanks!
