### ISSUE TITLE
Remove check to not stop null, 2, and 3 digit ISIC values in column `isic_4digit` 

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltIndicator#629]
Dear @maurolepore,

`isic_4digit` column can now have string length of null, 2 and 3 as well. Hence, I would like you to remove below check after my work on this [PR](https://github.com/2DegreesInvesting/tiltIndicatorBefore/pull/44) which closes this issue: https://github.com/2DegreesInvesting/tiltIndicatorBefore/issues/17. Will it be an issue if null, 2, and 3 digit isics will be used to calculate risk categories form the their `profile_ranking` column?

Thanks! Please let me know if there any questions!

https://github.com/2DegreesInvesting/tiltIndicator/blob/4eda6ad50bde5b200d814136ea94693c386b4a1c/R/emissions_profile_any_at_product_level.R#L32

**Comment by maurolepore** [comment]
Looks like you're in context. How about you submit a PR that removes that check and see what breaks?

**Comment by kalashsinghal** [comment]
@maurolepore Not every PR would need a change. Its more of a data requirement thing that changes based on decisions from Anne.

If you are not working on any urgent issue at the moment, may you please create a PR for this and let me know if something break or not? Please use a sample dataset of null and 2 digit ISIC and share with me the reprex of the output. Thanks a lot!

**Comment by maurolepore** [comment]
The PR is pending your review.

**Comment by AnneSchoenauer** [comment]
Hi both - sorry to jump in again but just to make sure - the 2 digit, and 3digits ISICs plus the NAs are not used for any profile_ranking, right @kalashsinghal?

**Comment by kalashsinghal** [comment]
@AnneSchoenauer Yes you are right! The 2 digit, 3digit ISICs, and the NAs are not used for any profile_ranking.

**Comment by maurolepore** [comment]
@AnneSchoenauer so you think it's not useful to now allow isic values of any length?

**Comment by AnneSchoenauer** [comment]
@maurolepore it is useful to allow it in the data, however, for the profile ranking it is not useful and won't be used.
