### ISSUE TITLE
Reviewing the illustrative plots and prioritise them

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltIndicator#647]
Dear @Tilmon, 
I created this ticket here so that we don't forget to review the plots that we currently have but also agree on the next ones before @lindadelacombaz creates new ones. 
Thanks!
Anne

**Comment by Tilmon** [comment]
Hi @AnneSchoenauer , in preparation for tomorrow I sketched some alternative ways of depicting the bar chart with the profile / risk categories. Pls see attached, but we can also just discuss tomorrow. I think all other charts are good!


[tilt_plots_ideas.pptx](https://github.com/2DegreesInvesting/tiltIndicator/files/13980109/tilt_plots_ideas.pptx)

**Comment by AnneSchoenauer** [comment]
We prioritised as such: 

1) German map 
2) New staggered plot
3) New scatter plot (with financial data)
4) Sankey Plot (with financial data)
5) Descriptives 

- [ ] All first without finanical data - then with financial data.
- [ ] For all the same ToyData sets. 
- [ ] Benchmarks as something to choose. 
- [ ] All in the corporate design of _tilt_

@lindadelacombaz FYI
