### ISSUE TITLE
Should `emissions_profile_any_compute_profile_ranking()` be internal?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#661]
It no longer seems to belong to the [family of pre-processing helpers](https://2degreesinvesting.github.io/tiltIndicator/reference/index.html#pre-processing-helpers). From the perspective of tiltIndicator it's now an internal function (used inside an exported function). So we need to either not-export it or label it as internal (with `#' @keywords internal`) -- which exports the function but hides its documentation.

An alternative is to move it to another package -- e.g. tiltUtils  -- and export it there. That makes the function public from the perspective of tiltUtils but internal from the perspective of tiltindicator.

**Comment by kalashsinghal** [comment]
@maurolepore As mentioned my Anne here in this [comment](https://github.com/2DegreesInvesting/tiltIndicator/pull/644#issuecomment-1878745892), We need the `profile_ranking` column in our final output. Hence, `emissions_profile_any_compute_profile_ranking()` can remain internal to tiltIndicator as `profile_ranking` is present in the final output.
