### ISSUE TITLE
Create a list of data requirements for calculation of indicators

### ISSUE THREAD

**Issue by ysherstyuk** [2DegreesInvesting/tiltIndicator#672]
Hi @kalashsinghal and @AnneSchoenauer 

To start building logical data model, I would like to get a list of data attributes which are necessary for calculating indicators. 

The data attributes need to be based on the methodology, but independent of how exactly they are used to calculate indicators, so we are free to think how the data should be structured. The idea is also to zoom out from the current way of how indicators are calculated so we can build a data model independent from the calculations.

I have attached an excel with the list [Data Requirements.xlsx](https://github.com/2DegreesInvesting/tiltIndicator/files/13948325/Data.Requirements.xlsx). Can you please fill in the first column only. 

The examples of the data attributes are company_id, company_name and address.

Hope the description is clear and otherwise reach out:)

Thank you!

**Comment by kalashsinghal** [comment]
@ysherstyuk I am assigning you this issue because I have sent you the data requirements file via email. Please create separate follow-up issues if you would like me to work on this task even further. Thanks!

**Comment by maurolepore** [comment]
From the previous comment it seems this issue is now closed. If not please feel free to reopen but consider if the best repo is tiltIndicator or elsewhere. Note the goal of the tiltIndicator package is not to host or develop real data.
