### ISSUE TITLE
Remove duplicate input_name from upstream profile product-level results and re-calculate company-level results

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#717]
Dear @kalashsinghal , 

as discussed in our Huddle, please modify the output of the upstream indicator results that Bob & Sven computed on product- and company-level in the following way: 

- remove duplicated `input_name` for each `companies_id `x `ep_product ` x `benchmark `- combination. You can just call `distinct()` and remove the duplicates randomly (emission_profile_upstream_on_product_level_ING.csv & sector_profile_upstream_on_product_level_ING.csv)
- calculate company-level results again based on new product-level results. (emission_profile_upstream_on_company_level_ING.csv & sector_profile_upstream_on_company_level_ING.csv)

Please not that both can be done "quick & dirty", i.e. this won't be a permanent change to the indicator code but is only a required last minute change to the output we want to show in a workshop next week. 

Please prioritize this over your other tasks and let me know if you run into problems. 

Data can be found here: [https://drive.google.com/drive/folders/10q6wOK8NWXHW5CE7_Zt2rEavFj8F64b_](https://drive.google.com/drive/folders/10q6wOK8NWXHW5CE7_Zt2rEavFj8F64b_ )

Thanks!

cc' @AnneSchoenauer

**Comment by Tilmon** [comment]
@kalashsinghal I added the file names + edited the first bullet by adding "x `benchmark`".

**Comment by kalashsinghal** [comment]
Results are provided via slack
