### ISSUE TITLE
Test that the output at company level can have `value` other than `0` in "high" AND ("medium" OR "low")

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#730]
Transfered from https://github.com/2DegreesInvesting/tiltIndicator/pull/639#issuecomment-1956211556 because it stands alone as a separate issue.

--

Create toy datasets that passed to our real code would generate an output at company level with value different than 0 in two of these: "high", "medium", and "low"? For example, I would want value to be `c(1/3, 1/3, 1/3)` where risk_category is c("high", "medium", NA), respectively. 

Conceptually it seems possible as Tilman and Anne "draw" such results but in practice I fail to do that -- even if I create inputs that look almost identical to what they draw. In the best case my failure is simply due to my poor understanding of the data and methodology, but in the worst case it is because of a bug in the code. In any case it will be beneficial to have a  conversation with @Tilmon and @AnneSchoenauer  about our data and code and turn that conversation into a reproducible example that I can write as a test.

@Tilmon note we're currently working on substantial changes to the code. This means that the results using the `main` branch (the one you install with the [normal installation instructions](https://2degreesinvesting.github.io/tiltIndicator/#installation)) are substantially different from the results we expect from our work in progress. So if you attempt to write a reproducible example you may either wait until we merge the ongoing PRs or you install the code directly from the PR with something like this:

```r
# Install the code from this PR: https://github.com/2DegreesInvesting/tiltIndicator/pull/729
pak::pak("2DegreesInvesting/tiltIndicator#729")
```

If you're struggling with [reprex](https://reprex.tidyverse.org/) let me konw and we coordinate a meeting.

**Comment by Tilmon** [comment]
Hi @maurolepore the installation of the development version doesn't work. Do you know how to fix it? See screenshots below (partially overlapping to give you the full picture): 



![Image](https://github.com/2DegreesInvesting/tiltIndicator/assets/88719608/fc2b071f-edb9-4f75-b761-42d410da9bd4)


![Image](https://github.com/2DegreesInvesting/tiltIndicator/assets/88719608/47af5ba6-c2a2-452d-9a7b-b80aa6304fef)

Also, could you give me an example how to best create the toy data in a way that it's useful for you? I think what we would need is a company with 3 products with 3 very different co2_footprints to make sure they are in different risk categories. If you could direct me to a similar reprex you created in the past or show me how to best do it, that would be great! Then I'm more than happy to play around with the data.

**Comment by maurolepore** [comment]
tt01.

**Comment by maurolepore** [comment]
Closed by https://github.com/2DegreesInvesting/tiltIndicator/pull/737
