### ISSUE TITLE
Check why some `companies_id` have NA in `country` in tiltIndicatorBefore

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#744]
(This should be in tiltIndicatorBefore but I can't transfer it to that repo for some reason, so pls do it yourself)

Hi @kalashsinghal , 

Mauro found in this comment https://github.com/2DegreesInvesting/tiltOutput/issues/1#issuecomment-1991633387 that there are some `companies_id `with NA in `country`. This shouldn't be the case, as in tiltData every `companies_id `has a corresponding `country`. 

Can you pls check where this originates from? 

Thanks!

cc' @AnneSchoenauer @maurolepore

**Comment by maurolepore** [comment]
@Tilmon see https://github.com/2DegreesInvesting/tiltOutput/issues/1#issuecomment-1991814366

I think the important `country` column (with no `NA`s) is passed to tiltIndicatorAfter via the argument `europages_companies` -- not via the argument `companies`. 

I'll assume my comment solves this issue  (if anything what needs to be done is to remove the confusing `country` column from the `companies` dataset).
