### ISSUE TITLE
Warn if using thresholds other than default

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#751]
Hey @maurolepore , 

a couple of times now we had the issue that the same thresholds were used in the sector_profile() for 2030 and 2050, while they should actually have different thresholds. 

Is there any way to ensure in the code that the user uses different thresholds? Or at least to ensure the user makes an active decision upon it?

**Comment by Tilmon** [comment]
Acc. to discussion from today's sprint: 
@maurolepore please include a warning message into the code if the user adjusts default settings for thresholds.

**Comment by maurolepore** [comment]
Closed by https://github.com/2DegreesInvesting/tiltWorkflows/pull/146
