### ISSUE TITLE
Generate all tilt output data after completion of webtool-relevant tickets

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#783]
Hi @maurolepore  @kalashsinghal ,

this is a ticket to create all tilt output data for the webtool, after completion of all the open issues that will still affect the output, such as: 

- [ ] 2DegreesInvesting/tiltIndicatorAfter#194
- [ ] #739 
- [ ] 2DegreesInvesting/tiltIndicatorAfter#242)
- [ ] **OPTIONAL** 2DegreesInvesting/tiltIndicatorAfter#244)

Output generation should be aimed for until end of this sprint (2024-05-24).

cc' @AnneSchoenauer

**Comment by AnneSchoenauer** [comment]
@Tilmon just to understand - the name of the ticket means that you want Mauro first to work on the webtool? Or only on the tickets that are open now? My understanding would be: open tickets --> output --> webtool but I may be wrong?

**Comment by Tilmon** [comment]
Hey @AnneSchoenauer no you are right! The idea is to finish the tickets in the description first, then create output, then work on webtool. If you think the ticket title is counterintuitive, feel free to adjust it! What I meant was to create the data after all tickets are done that are relevant for the final data in the webtool (in short "webtool-relevant"). But maybe it's not very clear...

**Comment by kalashsinghal** [comment]
This ticket seems not relevant, hence I will close it
