### ISSUE TITLE
Investigate why `emission_profile()` yields `co2e_lower ` and `co2e_upper` between 37 & 97% instead of the expected max ~20-30%

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#794]
Dear @kalashsinghal or @maurolepore , 

in this comment https://github.com/2DegreesInvesting/tiltTransitionRisk/pull/16#issuecomment-2154502947 I describe the following:

> When reproducing the output, I saw that emission_profile() adds 37% and 97% noise to co2e_lower and co2e_upper... I thought this has been changed in the past to less noise? It seems odd to me that if a co2_footprint is 300, the co2e_lower is almost 0...

I thought we agreed on a range that does not exceed ~20-30%. Can one of you investigate why the range is so large? I'm tagging both of you as I'm not sure who'd be the best to investigate this. But can one of you please have a look at it before tomorrow's sprint? 

Thanks!

**Comment by kalashsinghal** [comment]
@maurolepore As you have worked on the co2 range issue in the past, it will be much faster for you to resolve this issue. Hence, I request you to investigate this issue further. Please use this [reprex](https://github.com/2DegreesInvesting/tiltTransitionRisk/pull/16#issue-2338679057) for analysing the issue! Thanks!

**Comment by maurolepore** [comment]
@Tilmon, 

The noise can't be fixed because it depends on the data, so the noise you see with toy data doesn't predict the noise you'll see with real data. (This comment might ring from previous conversations about this topic.) We can't predict the noise but we can control it through trial and error.

<details><summary>reprex</summary>

``` r
# SETUP

library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)
library(tiltToyData)
library(tiltIndicatorAfter)

# Is this the version you have?
packageVersion("tiltIndicatorAfter")
#> [1] '0.0.0.9042'

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())



# INTERESTING

# 1. Allow reproducing "random" numbers
set.seed(1)
# 2. Try some amount of jitter
options(tiltIndicatorAfter.set_jitter_amount = 1)
# 3. Compute
profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
) |> 
  unnest_product() |> 
  mutate(co2_diff = co2e_upper - co2e_lower) |> 
  select(matches(c("benchmark", "co2"))) |> 
  head()
#> # A tibble: 6 × 4
#>   benchmark        co2e_lower co2e_upper co2_diff
#>   <chr>                 <dbl>      <dbl>    <dbl>
#> 1 all                   161.        550.     389.
#> 2 isic_4digit            33.5       568.     535.
#> 3 tilt_sector           190.        304.     115.
#> 4 unit                  230.        477.     247.
#> 5 unit_isic_4digit      162.        374.     212.
#> 6 unit_tilt_sector      292.        493.     201.

# 4. Evaluate: If OK we're done, else tweak the amount of jitter

# Too large. Try smaller amount ...

# 1. Allow reproducing "random" numbers
set.seed(1)
# 2. Try some amount of jitter
options(tiltIndicatorAfter.set_jitter_amount = 0.01)
# 3. Compute
profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
) |> 
  unnest_product() |> 
  mutate(co2_diff = co2e_upper - co2e_lower) |> 
  select(matches(c("benchmark", "co2"))) |> 
  head()
#> # A tibble: 6 × 4
#>   benchmark        co2e_lower co2e_upper co2_diff
#>   <chr>                 <dbl>      <dbl>    <dbl>
#> 1 all                    301.       305.     3.89
#> 2 isic_4digit            300.       305.     5.35
#> 3 tilt_sector            302.       303.     1.15
#> 4 unit                   302.       305.     2.47
#> 5 unit_isic_4digit       301.       303.     2.12
#> 6 unit_tilt_sector       303.       305.     2.01

# 4. Evaluate: If OK we're done, else tweak the amount of jitter
```

<sup>Created on 2024-06-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>


</details>

BTW

How did you learn about the noise? 

I ask because tiltIndicatorAfter no longer reports noise since v0.0.0.9038 ([changelog](https://2degreesinvesting.github.io/tiltIndicatorAfter/news/index.html#tiltindicatorafter-0009038-2024-05-06)). If you see a message reporting noise, you need to update your R packages or use a fresh R environment (e.g. on posit.cloud).

**Comment by Tilmon** [comment]
@maurolepore , OK, thanks for the info. But what's the noise with real data again then? Is it somewhere approx. betwenn 20 & 30%? 

I learned about the noise when reproducing the the example from Kalash's comment https://github.com/2DegreesInvesting/tiltTransitionRisk/pull/16#issue-2338679057. 

Thanks for the hint! Next time I'll make sure to update the R packages. I also have to update my R I believe.

**Comment by maurolepore** [comment]
@Tilmon 

It depends on the `amount` of jitter. If your target is 20-30%, then we'll aim for that next time we run `profile_emissions()` with real data. To reach that target we'll follow the experimental approach I showed in the reprex above -- basically guess and `amount` of jitter then adjust accordingly.

I recognize this feature is confusing and costs us a lot of effort. I think it will help to show the noise explicitly in the data. A while ago I recorded that idea here:

* https://github.com/2DegreesInvesting/tiltAddCO2/issues/1

It seems to have a greater priority that I had anticipated.

**Comment by Tilmon** [comment]
@maurolepore , OK!

> I recognize this feature is confusing and costs us a lot of effort. I think it will help to show the noise explicitly in the data. A while ago I recorded that idea here:
> 
> https://github.com/2DegreesInvesting/tiltIndicatorAfter/pull/236

You mean adding a column in the output data that shows the noise? We would need to remove that for the banks again, because otherwise they can calculate the "true" value with that information...

But would be good to find a way that we don't forget about it when creating data. E.g., I haven't had it on my radar for the Bundesbank data creation that we need to find the right amount via trial and error again. Let's discuss in the tech sprint!

**Comment by maurolepore** [comment]
Looks like we can close this issue now. The conversation resulted in a couple of issues that I'll follow up on.

* 2DegreesInvesting/tiltAddCO2#1
