### ISSUE TITLE
T5 continue with ICTR (Input Carbon TR Indicator)

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#85]
Review methodology before taking over technical work: [https://drive.google.com/drive/u/0/folders/1aPUjlbCcJ6GBZbzVV1fqXfGEUNFxUsYw](https://drive.google.com/drive/u/0/folders/1aPUjlbCcJ6GBZbzVV1fqXfGEUNFxUsYw)

After that, pick up ICTR MVP from Tilman and finish it

Step by step: 

1. Review files bookmarked in tilt-indicators channel. 
2. Review PCTR indicator for reference
3. Review current status of ICTR
4. Revise the ICTR. 
5. Fill out [mvp documentation template](https://drive.google.com/drive/u/0/folders/1C0hffilt42OoJRAc6YENT7oH4YJwFlXM) for input carbon indicator

Please find the PCTR indicator here: 

[pctr_main_v2.zip](https://github.com/2DegreesInvesting/tiltIndicator/files/11146504/pctr_main_v2.zip)

Please find ICTR indicator here: 

[ictr_main_v2.zip](https://github.com/2DegreesInvesting/tiltIndicator/files/11156160/ictr_main_v2.zip)

**Comment by maurolepore** [comment]
I consider this issue done. That is, to provide an MVP that I can integrate and improve. Further work on this indicator will be reflected in a number of small issues.

Thanks @kalashsinghal
